-- ============================================================
-- DOCBD.INFO / BANGLADESH HEALTH PLATFORM
-- STEP 1 — CLEAN PRODUCTION FOUNDATION
-- New Supabase project only.
-- Idempotent: safe to run once on a fresh DB and safe to re-run.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- ENUMS
-- ------------------------------------------------------------
do $$ begin
  create type public.user_role as enum (
    'patient','doctor','chamber','hospital','ambulance',
    'verification_officer','admin','super_admin'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.account_status as enum ('active','suspended','banned');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.provider_status as enum ('pending','approved','rejected','suspended');
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.verification_status as enum ('pending','approved','rejected','expired');
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------
-- PROFILES / AUTH
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'patient',
  account_status public.account_status not null default 'active',
  full_name text,
  email text,
  phone text,
  avatar_url text,
  date_of_birth date,
  gender text,
  blood_group text,
  public_phone boolean not null default false,
  district_id bigint,
  upazila_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_profiles_status on public.profiles(account_status);
create index if not exists idx_profiles_location on public.profiles(district_id, upazila_id);

-- ------------------------------------------------------------
-- BANGLADESH LOCATION MASTER
-- Full 64-district/upazila seed will be added in the location-data step.
-- IDs are bigint so the table remains compact and scalable.
-- ------------------------------------------------------------
create table if not exists public.divisions (
  id bigint generated by default as identity primary key,
  name_bn text not null,
  name_en text not null,
  slug text not null unique,
  is_active boolean not null default true
);

create table if not exists public.districts (
  id bigint generated by default as identity primary key,
  division_id bigint not null references public.divisions(id) on delete restrict,
  name_bn text not null,
  name_en text not null,
  slug text not null unique,
  is_active boolean not null default true
);

create table if not exists public.upazilas (
  id bigint generated by default as identity primary key,
  district_id bigint not null references public.districts(id) on delete restrict,
  name_bn text not null,
  name_en text not null,
  slug text not null,
  is_active boolean not null default true,
  unique(district_id, slug)
);

create index if not exists idx_districts_division on public.districts(division_id);
create index if not exists idx_upazilas_district on public.upazilas(district_id);

-- Add FKs after tables exist.
do $$ begin
  alter table public.profiles
    add constraint profiles_district_fk
    foreign key (district_id) references public.districts(id) on delete set null;
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.profiles
    add constraint profiles_upazila_fk
    foreign key (upazila_id) references public.upazilas(id) on delete set null;
exception when duplicate_object then null; end $$;

-- ------------------------------------------------------------
-- DOCTOR CORE
-- ------------------------------------------------------------
create table if not exists public.doctors (
  id uuid primary key references public.profiles(id) on delete cascade,
  professional_title text,
  degree text,
  designation text,
  bmdc_registration_no text,
  bmdc_verified boolean not null default false,
  bio text,
  consultation_fee numeric(12,2),
  experience_years integer,
  verification_status public.verification_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_doctors_bmdc
  on public.doctors(bmdc_registration_no)
  where bmdc_registration_no is not null and bmdc_registration_no <> '';

-- ------------------------------------------------------------
-- SPECIALTIES
-- ------------------------------------------------------------
create table if not exists public.specialties (
  id bigint generated by default as identity primary key,
  name_bn text not null,
  name_en text not null,
  slug text not null unique,
  icon_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists public.doctor_specialties (
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  specialty_id bigint not null references public.specialties(id) on delete restrict,
  is_primary boolean not null default false,
  primary key(doctor_id, specialty_id)
);

create index if not exists idx_doctor_specialties_specialty
  on public.doctor_specialties(specialty_id);

-- ------------------------------------------------------------
-- CHAMBER / HOSPITAL CORE
-- ------------------------------------------------------------
create table if not exists public.providers (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references public.profiles(id) on delete set null,
  provider_type text not null check (provider_type in ('chamber','hospital')),
  name_bn text not null,
  name_en text,
  slug text not null unique,
  logo_url text,
  banner_url text,
  phone text,
  email text,
  address text,
  district_id bigint references public.districts(id) on delete set null,
  upazila_id bigint references public.upazilas(id) on delete set null,
  latitude double precision,
  longitude double precision,
  map_url text,
  status public.provider_status not null default 'pending',
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_providers_location
  on public.providers(district_id, upazila_id);

create index if not exists idx_providers_geo
  on public.providers(latitude, longitude);

create table if not exists public.doctor_provider_links (
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  provider_id uuid not null references public.providers(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','removed')),
  invited_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key(doctor_id, provider_id)
);

create table if not exists public.chamber_schedules (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  provider_id uuid not null references public.providers(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  start_time time,
  end_time time,
  fee numeric(12,2),
  is_active boolean not null default true,
  unique(doctor_id, provider_id, day_of_week, start_time, end_time)
);

create index if not exists idx_schedules_provider on public.chamber_schedules(provider_id);
create index if not exists idx_schedules_doctor on public.chamber_schedules(doctor_id);

-- ------------------------------------------------------------
-- PATIENT LOCATION / LAST LOCATION
-- Exact location is private. Only authorized server-side/admin views.
-- ------------------------------------------------------------
create table if not exists public.user_locations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  district_id bigint references public.districts(id) on delete set null,
  upazila_id bigint references public.upazilas(id) on delete set null,
  accuracy_meters numeric(10,2),
  source text not null default 'gps'
    check (source in ('gps','manual','network')),
  recorded_at timestamptz not null default now()
);

create index if not exists idx_user_locations_user_time
  on public.user_locations(user_id, recorded_at desc);

-- Current location is kept on a dedicated row to avoid unbounded writes.
create table if not exists public.user_current_locations (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  district_id bigint references public.districts(id) on delete set null,
  upazila_id bigint references public.upazilas(id) on delete set null,
  accuracy_meters numeric(10,2),
  source text not null default 'gps'
    check (source in ('gps','manual','network')),
  updated_at timestamptz not null default now()
);

create index if not exists idx_current_locations_geo
  on public.user_current_locations(latitude, longitude);

-- ------------------------------------------------------------
-- APPOINTMENT FOUNDATION
-- ------------------------------------------------------------
create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.profiles(id) on delete cascade,
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  provider_id uuid references public.providers(id) on delete set null,
  appointment_date date not null,
  start_time time,
  end_time time,
  patient_note text,
  status text not null default 'pending'
    check (status in ('pending','confirmed','rejected','cancelled','completed','no_show')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_appointments_patient
  on public.appointments(patient_id, appointment_date desc);

create index if not exists idx_appointments_doctor
  on public.appointments(doctor_id, appointment_date desc);

create index if not exists idx_appointments_provider
  on public.appointments(provider_id, appointment_date desc);

-- ------------------------------------------------------------
-- NOTIFICATION FOUNDATION
-- ------------------------------------------------------------
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  type text not null,
  title_bn text not null,
  body_bn text,
  data jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_recipient
  on public.notifications(recipient_id, created_at desc);

-- ------------------------------------------------------------
-- REFERRAL FOUNDATION
-- ------------------------------------------------------------
create table if not exists public.referral_codes (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_user_id uuid references public.profiles(id) on delete set null,
  referral_code text not null,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists idx_referrals_referrer
  on public.referrals(referrer_id, created_at desc);

-- ------------------------------------------------------------
-- AUDIT LOG
-- ------------------------------------------------------------
create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_created
  on public.admin_audit_logs(created_at desc);

-- ------------------------------------------------------------
-- UPDATED_AT HELPER
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_doctors_updated_at on public.doctors;
create trigger trg_doctors_updated_at before update on public.doctors
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_providers_updated_at on public.providers;
create trigger trg_providers_updated_at before update on public.providers
for each row execute procedure public.set_updated_at();

drop trigger if exists trg_appointments_updated_at on public.appointments;
create trigger trg_appointments_updated_at before update on public.appointments
for each row execute procedure public.set_updated_at();

-- ------------------------------------------------------------
-- AUTO PROFILE ON AUTH SIGNUP
-- ------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role public.user_role;
begin
  requested_role := case new.raw_user_meta_data ->> 'intended_role'
    when 'doctor' then 'doctor'::public.user_role
    when 'hospital' then 'hospital'::public.user_role
    when 'ambulance' then 'ambulance'::public.user_role
    else 'patient'::public.user_role
  end;

  insert into public.profiles(id, role, full_name, email, phone)
  values (
    new.id,
    requested_role,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.email,
    coalesce(new.phone,new.raw_user_meta_data ->> 'phone')
  )
  on conflict (id) do nothing;

  if requested_role='doctor' then
    insert into public.doctors(id,verification_status)
    values(new.id,'pending')
    on conflict(id) do nothing;
  end if;

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public,anon,authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ------------------------------------------------------------
-- ROLE HELPERS
-- ------------------------------------------------------------
create or replace function public.is_admin_or_above()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid()
      and role in ('admin','super_admin')
      and account_status = 'active'
  );
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists(
    select 1 from public.profiles
    where id = auth.uid()
      and role = 'super_admin'
      and account_status = 'active'
  );
$$;

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.doctors enable row level security;
alter table public.specialties enable row level security;
alter table public.doctor_specialties enable row level security;
alter table public.providers enable row level security;
alter table public.doctor_provider_links enable row level security;
alter table public.chamber_schedules enable row level security;
alter table public.user_locations enable row level security;
alter table public.user_current_locations enable row level security;
alter table public.appointments enable row level security;
alter table public.notifications enable row level security;
alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.divisions enable row level security;
alter table public.districts enable row level security;
alter table public.upazilas enable row level security;

-- Public location master.
drop policy if exists "locations_public_select" on public.divisions;
create policy "locations_public_select" on public.divisions for select using (is_active);

drop policy if exists "districts_public_select" on public.districts;
create policy "districts_public_select" on public.districts for select using (is_active);

drop policy if exists "upazilas_public_select" on public.upazilas;
create policy "upazilas_public_select" on public.upazilas for select using (is_active);

drop policy if exists "specialties_public_select" on public.specialties;
create policy "specialties_public_select" on public.specialties for select using (is_active);

-- Profiles: own profile + admins. Public directory fields will later use
-- dedicated safe RPC/views rather than exposing all profile fields.
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles for select
using (id = auth.uid() or public.is_admin_or_above());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin" on public.profiles for update
using (id = auth.uid() or public.is_admin_or_above())
with check (id = auth.uid() or public.is_admin_or_above());

-- Profile changes use field-specific SECURITY DEFINER RPCs. This prevents a
-- signed-in user from directly changing role/account_status/admin-only fields.
revoke update on table public.profiles from public,anon,authenticated;

-- Doctor/provider data: public read only for approved/active records.
drop policy if exists "doctors_public_approved_select" on public.doctors;
create policy "doctors_public_approved_select" on public.doctors for select
using (
  verification_status = 'approved'
  or id = auth.uid()
  or public.is_admin_or_above()
);

drop policy if exists "doctors_owner_insert" on public.doctors;
create policy "doctors_owner_insert" on public.doctors for insert
with check (id = auth.uid());

drop policy if exists "doctors_owner_update" on public.doctors;
create policy "doctors_owner_update" on public.doctors for update
using (id = auth.uid() or public.is_admin_or_above())
with check (id = auth.uid() or public.is_admin_or_above());

drop policy if exists "providers_public_approved_select" on public.providers;
create policy "providers_public_approved_select" on public.providers for select
using (
  status = 'approved'
  or owner_user_id = auth.uid()
  or public.is_admin_or_above()
);

drop policy if exists "providers_owner_insert" on public.providers;
create policy "providers_owner_insert" on public.providers for insert
with check (owner_user_id = auth.uid() or public.is_admin_or_above());

drop policy if exists "providers_owner_update" on public.providers;
create policy "providers_owner_update" on public.providers for update
using (owner_user_id = auth.uid() or public.is_admin_or_above())
with check (owner_user_id = auth.uid() or public.is_admin_or_above());

-- Links/schedules.
drop policy if exists "doctor_provider_links_participants" on public.doctor_provider_links;
create policy "doctor_provider_links_participants" on public.doctor_provider_links for select
using (
  doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
);

drop policy if exists "doctor_provider_links_manage" on public.doctor_provider_links;
create policy "doctor_provider_links_manage" on public.doctor_provider_links for all
using (
  doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
)
with check (
  doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
);

drop policy if exists "schedules_public_approved" on public.chamber_schedules;
create policy "schedules_public_approved" on public.chamber_schedules for select
using (
  exists(
    select 1 from public.doctors d
    where d.id = doctor_id and d.verification_status = 'approved'
  )
  or doctor_id = auth.uid()
  or public.is_admin_or_above()
);

drop policy if exists "schedules_owner_manage" on public.chamber_schedules;
create policy "schedules_owner_manage" on public.chamber_schedules for all
using (doctor_id = auth.uid() or public.is_admin_or_above())
with check (doctor_id = auth.uid() or public.is_admin_or_above());

-- Exact user location: NEVER public.
drop policy if exists "user_locations_own_or_superadmin" on public.user_locations;
create policy "user_locations_own_or_superadmin" on public.user_locations for all
using (user_id = auth.uid() or public.is_super_admin())
with check (user_id = auth.uid() or public.is_super_admin());

drop policy if exists "current_location_own_or_superadmin" on public.user_current_locations;
create policy "current_location_own_or_superadmin" on public.user_current_locations for all
using (user_id = auth.uid() or public.is_super_admin())
with check (user_id = auth.uid() or public.is_super_admin());

-- Appointments: patient/doctor/provider participants + admins.
drop policy if exists "appointments_participants" on public.appointments;
create policy "appointments_participants" on public.appointments for select
using (
  patient_id = auth.uid()
  or doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
);

drop policy if exists "appointments_patient_insert" on public.appointments;
create policy "appointments_patient_insert" on public.appointments for insert
with check (patient_id = auth.uid());

drop policy if exists "appointments_participant_update" on public.appointments;
create policy "appointments_participant_update" on public.appointments for update
using (
  patient_id = auth.uid()
  or doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
)
with check (
  patient_id = auth.uid()
  or doctor_id = auth.uid()
  or exists(select 1 from public.providers p where p.id = provider_id and p.owner_user_id = auth.uid())
  or public.is_admin_or_above()
);

-- Notifications.
drop policy if exists "notifications_recipient_select" on public.notifications;
create policy "notifications_recipient_select" on public.notifications for select
using (recipient_id = auth.uid() or public.is_admin_or_above());

drop policy if exists "notifications_recipient_update" on public.notifications;
create policy "notifications_recipient_update" on public.notifications for update
using (recipient_id = auth.uid() or public.is_admin_or_above())
with check (recipient_id = auth.uid() or public.is_admin_or_above());

-- Referrals: users can see their own referral records.
drop policy if exists "referral_codes_own" on public.referral_codes;
create policy "referral_codes_own" on public.referral_codes for all
using (user_id = auth.uid() or public.is_admin_or_above())
with check (user_id = auth.uid() or public.is_admin_or_above());

drop policy if exists "referrals_own_or_admin" on public.referrals;
create policy "referrals_own_or_admin" on public.referrals for select
using (referrer_id = auth.uid() or referred_user_id = auth.uid() or public.is_admin_or_above());

drop policy if exists "referrals_insert" on public.referrals;
create policy "referrals_insert" on public.referrals for insert
with check (referrer_id = auth.uid() or public.is_admin_or_above());

-- Audit: admin/super admin only.
drop policy if exists "audit_superadmin_only" on public.admin_audit_logs;
create policy "audit_superadmin_only" on public.admin_audit_logs for select
using (public.is_super_admin());

-- ------------------------------------------------------------
-- BOOTSTRAP
-- After first Auth user is created, Super Admin can be set ONCE:
--
-- update public.profiles
-- set role='super_admin'
-- where id=(select id from auth.users where email='YOUR_EMAIL');
--
-- This statement should be executed manually in Supabase SQL Editor.
-- ------------------------------------------------------------

-- Seed core specialties (Bangla-first).
insert into public.specialties(name_bn,name_en,slug,sort_order) values
('মেডিসিন','Medicine','medicine',1),
('হৃদরোগ','Cardiology','cardiology',2),
('চক্ষু','Ophthalmology','ophthalmology',3),
('দন্ত চিকিৎসা','Dentistry','dentistry',4),
('শিশু রোগ','Pediatrics','pediatrics',5),
('স্ত্রী ও প্রসূতি রোগ','Obstetrics & Gynecology','obgyn',6),
('হাড় ও জয়েন্ট','Orthopedics','orthopedics',7),
('চর্মরোগ','Dermatology','dermatology',8),
('নাক-কান-গলা','ENT','ent',9),
('স্নায়ুরোগ','Neurology','neurology',10)
on conflict(slug) do nothing;

-- ============================================================
-- END STEP 1 FOUNDATION
-- ============================================================
