-- ============================================================
-- STEP 9 — HOMEPAGE DISCOVERY + CMS FOUNDATION
-- Run ONLY this file after Step 08 has completed successfully.
-- Previous migrations are stored separately.
-- ============================================================

-- ------------------------------------------------------------
-- DISCOVERY TOPICS
-- Patient-friendly disease/organ labels mapped to specialties.
-- ------------------------------------------------------------
create table if not exists public.discovery_topics (
  id bigint generated by default as identity primary key,
  name_bn text not null,
  name_en text,
  slug text not null unique,
  icon text,
  description_bn text,
  search_keywords text[] not null default '{}'::text[],
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discovery_topic_specialties (
  topic_id bigint not null
    references public.discovery_topics(id) on delete cascade,
  specialty_id bigint not null
    references public.specialties(id) on delete cascade,
  primary key(topic_id, specialty_id)
);

create index if not exists idx_discovery_topics_active_order
  on public.discovery_topics(is_active, sort_order, id);

create index if not exists idx_discovery_topic_specialty
  on public.discovery_topic_specialties(specialty_id, topic_id);

-- ------------------------------------------------------------
-- HOMEPAGE SECTION ENGINE
-- filter_config is intentionally JSON so new discovery rules can
-- be added without a schema migration. The public function below
-- returns only active sections.
-- ------------------------------------------------------------
create table if not exists public.homepage_sections (
  id uuid primary key default gen_random_uuid(),
  section_key text not null unique,
  title_bn text not null,
  title_en text,
  description_bn text,
  data_source text not null
    check (data_source in ('doctor','provider','ambulance','topic','custom')),
  filter_config jsonb not null default '{}'::jsonb
    check (jsonb_typeof(filter_config) = 'object'),
  view_all_path text,
  card_limit smallint not null default 10
    check (card_limit between 1 and 30),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_homepage_sections_active_order
  on public.homepage_sections(is_active, sort_order, id);

-- ------------------------------------------------------------
-- BANNERS
-- image_path stores a storage object path, not a provider URL.
-- This keeps a future Supabase Storage -> R2 move inexpensive.
-- ------------------------------------------------------------
create table if not exists public.homepage_banners (
  id uuid primary key default gen_random_uuid(),
  title_bn text not null,
  title_en text,
  subtitle_bn text,
  subtitle_en text,
  image_path text not null,
  image_alt_bn text,
  target_url text,
  district_id bigint references public.districts(id) on delete set null,
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create index if not exists idx_homepage_banners_public
  on public.homepage_banners(is_active, district_id, sort_order, starts_at, ends_at);

-- ------------------------------------------------------------
-- EDITABLE CONTENT PAGES + SITE SETTINGS
-- Legal pages are seeded as drafts so placeholder copy is never
-- accidentally published as a real policy.
-- ------------------------------------------------------------
create table if not exists public.content_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title_bn text not null,
  title_en text,
  body_bn text not null default '',
  body_en text,
  seo_title text,
  meta_description text,
  is_published boolean not null default false,
  updated_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  is_public boolean not null default false,
  description text,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- UPDATED_AT TRIGGERS
-- Reuses public.set_updated_at() from Step 01.
-- ------------------------------------------------------------
drop trigger if exists set_discovery_topics_updated_at on public.discovery_topics;
create trigger set_discovery_topics_updated_at
before update on public.discovery_topics
for each row execute function public.set_updated_at();

drop trigger if exists set_homepage_sections_updated_at on public.homepage_sections;
create trigger set_homepage_sections_updated_at
before update on public.homepage_sections
for each row execute function public.set_updated_at();

drop trigger if exists set_homepage_banners_updated_at on public.homepage_banners;
create trigger set_homepage_banners_updated_at
before update on public.homepage_banners
for each row execute function public.set_updated_at();

drop trigger if exists set_content_pages_updated_at on public.content_pages;
create trigger set_content_pages_updated_at
before update on public.content_pages
for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- ROW LEVEL SECURITY
-- Public visitors see only active/published content. Admin and
-- Super Admin can manage CMS records directly through Supabase.
-- ------------------------------------------------------------
alter table public.discovery_topics enable row level security;
alter table public.discovery_topic_specialties enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.homepage_banners enable row level security;
alter table public.content_pages enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "discovery_topics_public_read" on public.discovery_topics;
create policy "discovery_topics_public_read"
on public.discovery_topics for select
using (is_active or public.is_admin_or_above());

drop policy if exists "discovery_topics_admin_manage" on public.discovery_topics;
create policy "discovery_topics_admin_manage"
on public.discovery_topics for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

drop policy if exists "topic_specialties_public_read" on public.discovery_topic_specialties;
create policy "topic_specialties_public_read"
on public.discovery_topic_specialties for select
using (
  exists (
    select 1
    from public.discovery_topics t
    where t.id=topic_id and t.is_active
  )
  or public.is_admin_or_above()
);

drop policy if exists "topic_specialties_admin_manage" on public.discovery_topic_specialties;
create policy "topic_specialties_admin_manage"
on public.discovery_topic_specialties for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

drop policy if exists "homepage_sections_public_read" on public.homepage_sections;
create policy "homepage_sections_public_read"
on public.homepage_sections for select
using (is_active or public.is_admin_or_above());

drop policy if exists "homepage_sections_admin_manage" on public.homepage_sections;
create policy "homepage_sections_admin_manage"
on public.homepage_sections for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

drop policy if exists "homepage_banners_public_read" on public.homepage_banners;
create policy "homepage_banners_public_read"
on public.homepage_banners for select
using (
  (
    is_active
    and (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at > now())
  )
  or public.is_admin_or_above()
);

drop policy if exists "homepage_banners_admin_manage" on public.homepage_banners;
create policy "homepage_banners_admin_manage"
on public.homepage_banners for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

drop policy if exists "content_pages_public_read" on public.content_pages;
create policy "content_pages_public_read"
on public.content_pages for select
using (is_published or public.is_admin_or_above());

drop policy if exists "content_pages_admin_manage" on public.content_pages;
create policy "content_pages_admin_manage"
on public.content_pages for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

drop policy if exists "site_settings_public_read" on public.site_settings;
create policy "site_settings_public_read"
on public.site_settings for select
using (is_public or public.is_admin_or_above());

drop policy if exists "site_settings_admin_manage" on public.site_settings;
create policy "site_settings_admin_manage"
on public.site_settings for all
using (public.is_admin_or_above())
with check (public.is_admin_or_above());

-- Table privileges and RLS work together: visitors can read the
-- public rows; authenticated Admin/Super Admin users can mutate rows.
grant select on table
  public.discovery_topics,
  public.discovery_topic_specialties,
  public.homepage_sections,
  public.homepage_banners,
  public.content_pages,
  public.site_settings
to anon,authenticated;

grant insert,update,delete on table
  public.discovery_topics,
  public.discovery_topic_specialties,
  public.homepage_sections,
  public.homepage_banners,
  public.content_pages,
  public.site_settings
to authenticated;

grant usage,select on sequence public.discovery_topics_id_seq
to authenticated;

-- ------------------------------------------------------------
-- DEFAULT HOMEPAGE LAYOUT
-- ON CONFLICT DO NOTHING preserves later admin customizations.
-- ------------------------------------------------------------
insert into public.homepage_sections(
  section_key,title_bn,title_en,data_source,filter_config,
  view_all_path,card_limit,sort_order
)
values
  ('district_doctors','আপনার জেলার ডাক্তার','Doctors in your district','doctor',
   '{"scope":"district","sort":"name"}'::jsonb,'/doctors',10,10),
  ('specialist_doctors','স্পেশালিস্ট ডাক্তার','Specialist doctors','doctor',
   '{"has_specialty":true,"sort":"name"}'::jsonb,'/doctors',10,20),
  ('consultant_doctors','কনসালটেন্ট','Consultants','doctor',
   '{"designation_contains":"consultant","sort":"name"}'::jsonb,'/doctors',10,30),
  ('professor_doctors','প্রফেসর ও শিক্ষক ডাক্তার','Professors and teaching doctors','doctor',
   '{"designation_group":"professor","sort":"name"}'::jsonb,'/doctors',10,40),
  ('new_doctors','নতুন যোগ হওয়া ডাক্তার','Newly added doctors','doctor',
   '{"sort":"newest"}'::jsonb,'/doctors',10,50),
  ('district_hospitals','আপনার জেলার জনপ্রিয় হাসপাতাল','Hospitals in your district','provider',
   '{"provider_type":"hospital","scope":"district","sort":"name"}'::jsonb,'/hospitals',10,60),
  ('nearby_ambulances','কাছের অ্যাম্বুলেন্স','Nearby ambulances','ambulance',
   '{"scope":"nearby","sort":"distance"}'::jsonb,'/ambulances',10,70)
on conflict(section_key) do nothing;

insert into public.content_pages(slug,title_bn,title_en,is_published)
values
  ('about','আমাদের সম্পর্কে','About us',false),
  ('terms','ব্যবহারের শর্তাবলি','Terms of use',false),
  ('privacy','গোপনীয়তা নীতি','Privacy policy',false),
  ('faq','সাধারণ প্রশ্ন','Frequently asked questions',false),
  ('help','সহায়তা','Help',false)
on conflict(slug) do nothing;

insert into public.site_settings(setting_key,setting_value,is_public,description)
values
  ('public_brand',
   '{"site_name_bn":"docbd.info","site_name_en":"docbd.info"}'::jsonb,
   true,'Public brand name'),
  ('social_links','{}'::jsonb,true,'Public social profile links'),
  ('default_location','{}'::jsonb,true,'Default district/upazila fallback')
on conflict(setting_key) do nothing;

-- ------------------------------------------------------------
-- PUBLIC HOMEPAGE CONFIGURATION
-- One round-trip for sections, active banners, topics and public
-- settings. Banner district NULL means platform-wide.
-- ------------------------------------------------------------
create or replace function public.get_homepage_configuration(
  p_district_id bigint default null
)
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'sections',coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',s.id,
          'key',s.section_key,
          'title_bn',s.title_bn,
          'title_en',s.title_en,
          'description_bn',s.description_bn,
          'data_source',s.data_source,
          'filter_config',s.filter_config,
          'view_all_path',s.view_all_path,
          'card_limit',s.card_limit
        ) order by s.sort_order,s.id
      )
      from public.homepage_sections s
      where s.is_active
    ),'[]'::jsonb),
    'banners',coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',b.id,
          'title_bn',b.title_bn,
          'title_en',b.title_en,
          'subtitle_bn',b.subtitle_bn,
          'subtitle_en',b.subtitle_en,
          'image_path',b.image_path,
          'image_alt_bn',b.image_alt_bn,
          'target_url',b.target_url
        ) order by b.sort_order,b.id
      )
      from public.homepage_banners b
      where b.is_active
        and (b.starts_at is null or b.starts_at <= now())
        and (b.ends_at is null or b.ends_at > now())
        and (b.district_id is null or b.district_id=p_district_id)
    ),'[]'::jsonb),
    'topics',coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id',t.id,
          'name_bn',t.name_bn,
          'name_en',t.name_en,
          'slug',t.slug,
          'icon',t.icon,
          'description_bn',t.description_bn,
          'search_keywords',t.search_keywords,
          'specialty_ids',coalesce((
            select jsonb_agg(ts.specialty_id order by ts.specialty_id)
            from public.discovery_topic_specialties ts
            where ts.topic_id=t.id
          ),'[]'::jsonb)
        ) order by t.sort_order,t.id
      )
      from public.discovery_topics t
      where t.is_active
    ),'[]'::jsonb),
    'settings',coalesce((
      select jsonb_object_agg(ss.setting_key,ss.setting_value)
      from public.site_settings ss
      where ss.is_public
    ),'{}'::jsonb)
  );
$$;

-- ------------------------------------------------------------
-- ADVANCED DOCTOR SEARCH
-- SECURITY DEFINER is deliberate: profiles contains private data,
-- so public callers receive only the explicitly listed safe fields.
-- Text query covers doctor, specialty, topic and location names.
-- ------------------------------------------------------------
create or replace function public.search_doctors_advanced(
  p_query text default null,
  p_district_id bigint default null,
  p_upazila_id bigint default null,
  p_specialty_ids bigint[] default null,
  p_degrees text[] default null,
  p_designations text[] default null,
  p_min_fee numeric default null,
  p_max_fee numeric default null,
  p_available_today boolean default false,
  p_sort text default 'name',
  p_limit integer default 20,
  p_offset integer default 0
)
returns table(
  doctor_id uuid,
  doctor_name text,
  avatar_url text,
  degree text,
  designation text,
  professional_title text,
  consultation_fee numeric,
  experience_years integer,
  district_id bigint,
  district_name_bn text,
  upazila_id bigint,
  upazila_name_bn text,
  specialties jsonb,
  available_today boolean,
  total_count bigint
)
language sql
stable
security definer
set search_path=public
as $$
  with matched as (
    select
      d.id as doctor_id,
      p.full_name as doctor_name,
      p.avatar_url,
      d.degree,
      d.designation,
      d.professional_title,
      d.consultation_fee,
      d.experience_years,
      p.district_id,
      dist.name_bn as district_name_bn,
      p.upazila_id,
      upz.name_bn as upazila_name_bn,
      d.created_at,
      coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id',sp.id,
            'name_bn',sp.name_bn,
            'name_en',sp.name_en,
            'slug',sp.slug,
            'is_primary',ds.is_primary
          ) order by ds.is_primary desc,sp.sort_order,sp.id
        )
        from public.doctor_specialties ds
        join public.specialties sp on sp.id=ds.specialty_id
        where ds.doctor_id=d.id and sp.is_active
      ),'[]'::jsonb) as specialties,
      exists (
        select 1
        from public.chamber_schedules cs
        join public.providers pr on pr.id=cs.provider_id
        where cs.doctor_id=d.id
          and cs.is_active
          and cs.day_of_week=extract(dow from now() at time zone 'Asia/Dhaka')::smallint
          and pr.status='approved'
          and pr.verified
      ) as available_today
    from public.doctors d
    join public.profiles p on p.id=d.id
    left join public.districts dist on dist.id=p.district_id
    left join public.upazilas upz on upz.id=p.upazila_id
    where d.verification_status='approved'
      and p.account_status='active'
      and (p_district_id is null or p.district_id=p_district_id)
      and (p_upazila_id is null or p.upazila_id=p_upazila_id)
      and (p_min_fee is null or d.consultation_fee >= p_min_fee)
      and (p_max_fee is null or d.consultation_fee <= p_max_fee)
      and (
        p_specialty_ids is null
        or cardinality(p_specialty_ids)=0
        or exists (
          select 1 from public.doctor_specialties ds
          where ds.doctor_id=d.id
            and ds.specialty_id=any(p_specialty_ids)
        )
      )
      and (
        p_degrees is null
        or cardinality(p_degrees)=0
        or exists (
          select 1 from unnest(p_degrees) requested_degree
          where d.degree ilike '%'||requested_degree||'%'
        )
      )
      and (
        p_designations is null
        or cardinality(p_designations)=0
        or exists (
          select 1 from unnest(p_designations) requested_designation
          where d.designation ilike '%'||requested_designation||'%'
        )
      )
      and (
        nullif(trim(p_query),'') is null
        or p.full_name ilike '%'||trim(p_query)||'%'
        or d.degree ilike '%'||trim(p_query)||'%'
        or d.designation ilike '%'||trim(p_query)||'%'
        or d.professional_title ilike '%'||trim(p_query)||'%'
        or dist.name_bn ilike '%'||trim(p_query)||'%'
        or dist.name_en ilike '%'||trim(p_query)||'%'
        or upz.name_bn ilike '%'||trim(p_query)||'%'
        or upz.name_en ilike '%'||trim(p_query)||'%'
        or exists (
          select 1
          from public.doctor_specialties ds
          join public.specialties sp on sp.id=ds.specialty_id
          where ds.doctor_id=d.id
            and (
              sp.name_bn ilike '%'||trim(p_query)||'%'
              or sp.name_en ilike '%'||trim(p_query)||'%'
            )
        )
        or exists (
          select 1
          from public.doctor_specialties ds
          join public.discovery_topic_specialties dts
            on dts.specialty_id=ds.specialty_id
          join public.discovery_topics dt on dt.id=dts.topic_id
          where ds.doctor_id=d.id
            and dt.is_active
            and (
              dt.name_bn ilike '%'||trim(p_query)||'%'
              or dt.name_en ilike '%'||trim(p_query)||'%'
              or exists (
                select 1 from unnest(dt.search_keywords) keyword
                where keyword ilike '%'||trim(p_query)||'%'
                   or trim(p_query) ilike '%'||keyword||'%'
              )
            )
        )
      )
  ), filtered as (
    select *
    from matched
    where not p_available_today or available_today
  )
  select
    f.doctor_id,
    f.doctor_name,
    f.avatar_url,
    f.degree,
    f.designation,
    f.professional_title,
    f.consultation_fee,
    f.experience_years,
    f.district_id,
    f.district_name_bn,
    f.upazila_id,
    f.upazila_name_bn,
    f.specialties,
    f.available_today,
    count(*) over() as total_count
  from filtered f
  order by
    case when p_sort='newest' then f.created_at end desc,
    case when p_sort='fee_low' then f.consultation_fee end asc nulls last,
    case when p_sort='fee_high' then f.consultation_fee end desc nulls last,
    f.doctor_name asc nulls last,
    f.doctor_id
  limit greatest(1,least(p_limit,100))
  offset greatest(p_offset,0);
$$;

-- Fixes the Step 03 district predicate and keeps private profile
-- columns protected behind an explicit safe return shape.
create or replace function public.doctors_by_area(
  p_district_id bigint default null,
  p_upazila_id bigint default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table(
  doctor_id uuid,
  doctor_name text,
  avatar_url text,
  degree text,
  designation text,
  consultation_fee numeric,
  district_id bigint,
  upazila_id bigint
)
language sql
stable
security definer
set search_path=public
as $$
  select d.id,p.full_name,p.avatar_url,d.degree,d.designation,
         d.consultation_fee,p.district_id,p.upazila_id
  from public.doctors d
  join public.profiles p on p.id=d.id
  where d.verification_status='approved'
    and p.account_status='active'
    and (p_district_id is null or p.district_id=p_district_id)
    and (p_upazila_id is null or p.upazila_id=p_upazila_id)
  order by p.full_name,d.id
  limit greatest(1,least(p_limit,100))
  offset greatest(p_offset,0);
$$;

-- Remove PostgreSQL's default PUBLIC function grant, then expose
-- only the RPCs that are intentionally part of the public API.
revoke all on function public.get_homepage_configuration(bigint)
  from public;
revoke all on function public.search_doctors_advanced(
  text,bigint,bigint,bigint[],text[],text[],numeric,numeric,boolean,text,integer,integer
) from public;
revoke all on function public.doctors_by_area(bigint,bigint,integer,integer)
  from public;

grant execute on function public.get_homepage_configuration(bigint)
  to anon,authenticated,service_role;
grant execute on function public.search_doctors_advanced(
  text,bigint,bigint,bigint[],text[],text[],numeric,numeric,boolean,text,integer,integer
) to anon,authenticated,service_role;
grant execute on function public.doctors_by_area(bigint,bigint,integer,integer)
  to anon,authenticated,service_role;

-- ============================================================
-- END STEP 9
-- ============================================================
