-- ============================================================
-- STEP 11 — REFERENCE DATA + STORAGE SECURITY + SELF-CHECKS
-- Generated by scripts/generate_step11_reference_data.mjs
-- Run ONLY this file after Step 10 has completed successfully.
-- ============================================================
-- Location source: Bangladesh Administrative Divisions Dataset
-- https://github.com/open-admin-data/bangladesh-administrative-divisions
-- CC-BY-4.0, snapshot updated 2026-06-01.
-- Cross-checked against Bangladesh National Portal district/upazila lists.
-- Source snapshot: 8 divisions, 64 districts, 495 upazilas.
-- ============================================================

-- ------------------------------------------------------------
-- LOCATION SOURCE CODES + COORDINATES
-- Existing identity IDs/FKs stay stable; source_code stores BBS-style codes.
-- ------------------------------------------------------------
alter table public.divisions add column if not exists source_code text;
alter table public.divisions add column if not exists latitude double precision;
alter table public.divisions add column if not exists longitude double precision;
alter table public.districts add column if not exists source_code text;
alter table public.districts add column if not exists latitude double precision;
alter table public.districts add column if not exists longitude double precision;
alter table public.upazilas add column if not exists source_code text;
alter table public.upazilas add column if not exists latitude double precision;
alter table public.upazilas add column if not exists longitude double precision;

create unique index if not exists ux_divisions_source_code
  on public.divisions(source_code) where source_code is not null;
create unique index if not exists ux_districts_source_code
  on public.districts(source_code) where source_code is not null;
create unique index if not exists ux_upazilas_source_code
  on public.upazilas(source_code) where source_code is not null;

with incoming(source_code,name_bn,name_en,slug,latitude,longitude) as (
values
  ('BD10','বরিশাল','Barishal','barishal',22.393,90.406),
  ('BD20','চট্টগ্রাম','Chattogram','chattogram',22.701,91.706),
  ('BD30','ঢাকা','Dhaka','dhaka',23.839,90.242),
  ('BD40','খুলনা','Khulna','khulna',22.838,89.305),
  ('BD45','ময়মনসিংহ','Mymensingh','mymensingh',24.848,90.382),
  ('BD50','রাজশাহী','Rajshahi','rajshahi',24.589,89.046),
  ('BD55','রংপুর','Rangpur','rangpur',25.78,89.054),
  ('BD60','সিলেট','Sylhet','sylhet',24.715,91.665)
)
insert into public.divisions(source_code,name_bn,name_en,slug,latitude,longitude,is_active)
select source_code,name_bn,name_en,slug,latitude,longitude,true from incoming
on conflict(slug) do update
set source_code=excluded.source_code,name_bn=excluded.name_bn,name_en=excluded.name_en,
    latitude=excluded.latitude,longitude=excluded.longitude,is_active=true;

with incoming(source_code,division_code,name_bn,name_en,slug,latitude,longitude) as (
values
  ('BD1004','BD10','বরগুনা','Barguna','barguna',22.128,90.11),
  ('BD1006','BD10','বরিশাল','Barishal','barishal',22.819,90.369),
  ('BD1009','BD10','ভোলা','Bhola','bhola',22.31,90.764),
  ('BD1042','BD10','ঝালকাঠি','Jhalokati','jhalokati',22.572,90.182),
  ('BD1078','BD10','পটুয়াখালী','Patuakhali','patuakhali',22.165,90.407),
  ('BD1079','BD10','পিরোজপুর','Pirojpur','pirojpur',22.532,89.992),
  ('BD2003','BD20','বান্দরবান','Bandarban','bandarban',21.805,92.365),
  ('BD2012','BD20','ব্রাহ্মণবাড়ীয়া','Brahmanbaria','brahmanbaria',23.953,91.083),
  ('BD2013','BD20','চাঁদপুর','Chandpur','chandpur',23.261,90.749),
  ('BD2015','BD20','চট্টগ্রাম','Chattogram','chattogram',22.447,91.819),
  ('BD2019','BD20','কুমিল্লা','Cumilla','cumilla',23.437,91.033),
  ('BD2022','BD20','কক্সবাজার','Cox''s Bazar','coxs-bazar',21.476,92.063),
  ('BD2030','BD20','ফেনী','Feni','feni',22.995,91.412),
  ('BD2046','BD20','খাগড়াছড়ি','Khagrachhari','khagrachhari',23.172,91.956),
  ('BD2051','BD20','লক্ষ্মীপুর','Lakshmipur','lakshmipur',22.851,90.854),
  ('BD2075','BD20','নোয়াখালী','Noakhali','noakhali',22.658,91.129),
  ('BD2084','BD20','রাঙ্গামাটি','Rangamati','rangamati',22.825,92.281),
  ('BD3026','BD30','ঢাকা','Dhaka','dhaka',23.788,90.251),
  ('BD3029','BD30','ফরিদপুর','Faridpur','faridpur',23.478,89.836),
  ('BD3033','BD30','গাজীপুর','Gazipur','gazipur',24.099,90.446),
  ('BD3035','BD30','গোপালগঞ্জ','Gopalganj','gopalganj',23.105,89.899),
  ('BD3048','BD30','কিশোরগঞ্জ','Kishoreganj','kishoreganj',24.378,90.943),
  ('BD3054','BD30','মাদারীপুর','Madaripur','madaripur',23.222,90.166),
  ('BD3056','BD30','মানিকগঞ্জ','Manikganj','manikganj',23.841,89.951),
  ('BD3059','BD30','মুন্সিগঞ্জ','Munshiganj','munshiganj',23.526,90.416),
  ('BD3067','BD30','নারায়ণগঞ্জ','Narayanganj','narayanganj',23.724,90.578),
  ('BD3068','BD30','নরসিংদী','Narsingdi','narsingdi',24.003,90.774),
  ('BD3082','BD30','রাজবাড়ী','Rajbari','rajbari',23.729,89.561),
  ('BD3086','BD30','শরিয়তপুর','Shariatpur','shariatpur',23.245,90.415),
  ('BD3093','BD30','টাঙ্গাইল','Tangail','tangail',24.358,90),
  ('BD4001','BD40','বাগেরহাট','Bagerhat','bagerhat',22.329,89.744),
  ('BD4018','BD40','চুয়াডাঙ্গা','Chuadanga','chuadanga',23.609,88.849),
  ('BD4041','BD40','যশোর','Jashore','jashore',23.089,89.175),
  ('BD4044','BD40','ঝিনাইদহ','Jhenaidah','jhenaidah',23.488,89.087),
  ('BD4047','BD40','খুলনা','Khulna','khulna',22.366,89.453),
  ('BD4050','BD40','কুষ্টিয়া','Kushtia','kushtia',23.926,89.018),
  ('BD4055','BD40','মাগুরা','Magura','magura',23.444,89.433),
  ('BD4057','BD40','মেহেরপুর','Meherpur','meherpur',23.794,88.707),
  ('BD4065','BD40','নড়াইল','Narail','narail',23.131,89.578),
  ('BD4087','BD40','সাতক্ষীরা','Satkhira','satkhira',22.308,89.143),
  ('BD4539','BD45','জামালপুর','Jamalpur','jamalpur',24.977,89.847),
  ('BD4561','BD45','ময়মনসিংহ','Mymensingh','mymensingh',24.699,90.43),
  ('BD4572','BD45','নেত্রকোনা','Netrakona','netrakona',24.871,90.845),
  ('BD4589','BD45','শেরপুর','Sherpur','sherpur',25.083,90.075),
  ('BD5010','BD50','বগুড়া','Bogura','bogura',24.824,89.38),
  ('BD5038','BD50','জয়পুরহাট','Joypurhat','joypurhat',25.093,89.084),
  ('BD5064','BD50','নওগাঁ','Naogaon','naogaon',24.9,88.752),
  ('BD5069','BD50','নাটোর','Natore','natore',24.381,89.087),
  ('BD5070','BD50','চাঁপাইনবাবগঞ্জ','Chapainababganj','chapainababganj',24.716,88.264),
  ('BD5076','BD50','পাবনা','Pabna','pabna',24.053,89.386),
  ('BD5081','BD50','রাজশাহী','Rajshahi','rajshahi',24.468,88.651),
  ('BD5088','BD50','সিরাজগঞ্জ','Sirajganj','sirajganj',24.392,89.601),
  ('BD5527','BD55','দিনাজপুর','Dinajpur','dinajpur',25.63,88.786),
  ('BD5532','BD55','গাইবান্ধা','Gaibandha','gaibandha',25.298,89.505),
  ('BD5549','BD55','কুড়িগ্রাম','Kurigram','kurigram',25.79,89.695),
  ('BD5552','BD55','লালমনিরহাট','Lalmonirhat','lalmonirhat',26.063,89.237),
  ('BD5573','BD55','নীলফামারী','Nilphamari','nilphamari',26.026,88.93),
  ('BD5577','BD55','পঞ্চগড়','Panchagarh','panchagarh',26.285,88.579),
  ('BD5585','BD55','রংপুর','Rangpur','rangpur',25.651,89.237),
  ('BD5594','BD55','ঠাকুরগাঁও','Thakurgaon','thakurgaon',25.99,88.345),
  ('BD6036','BD60','হবিগঞ্জ','Habiganj','habiganj',24.369,91.432),
  ('BD6058','BD60','মৌলভীবাজার','Moulvibazar','moulvibazar',24.481,91.916),
  ('BD6090','BD60','সুনামগঞ্জ','Sunamganj','sunamganj',24.94,91.346),
  ('BD6091','BD60','সিলেট','Sylhet','sylhet',24.92,91.988)
)
insert into public.districts(
  source_code,division_id,name_bn,name_en,slug,latitude,longitude,is_active
)
select i.source_code,d.id,i.name_bn,i.name_en,i.slug,i.latitude,i.longitude,true
from incoming i
join public.divisions d on d.source_code=i.division_code
on conflict(slug) do update
set source_code=excluded.source_code,division_id=excluded.division_id,
    name_bn=excluded.name_bn,name_en=excluded.name_en,
    latitude=excluded.latitude,longitude=excluded.longitude,is_active=true;

with incoming(source_code,district_code,name_bn,name_en,slug,latitude,longitude) as (
values
  ('BD20030004','BD2003','আলীকদম','Alikadam','alikadam',21.596,92.403),
  ('BD20030014','BD2003','বান্দরবান সদর','Bandarban Sadar','bandarban-sadar',22.065,92.233),
  ('BD20030051','BD2003','লামা','Lama','lama',21.81,92.212),
  ('BD20030073','BD2003','নাইক্ষ্যংছড়ি','Naikkhongchhari','naikkhongchhari',21.471,92.243),
  ('BD20030089','BD2003','রোয়াংছড়ি','Rowangchhari','rowangchhari',22.199,92.352),
  ('BD20030091','BD2003','রুমা','Ruma','ruma',22.008,92.449),
  ('BD20030095','BD2003','থানচি','Thanchi','thanchi',21.643,92.533),
  ('BD20120002','BD2012','আখাউড়া','Akhaura','akhaura',23.841,91.19),
  ('BD20120033','BD2012','আশুগঞ্জ','Ashuganj','ashuganj',24.018,91.018),
  ('BD20120004','BD2012','বাঞ্ছারামপুর','Banchharampur','banchharampur',23.781,90.807),
  ('BD20120007','BD2012','বিজয়নগর','Bijoynagar','bijoynagar',23.992,91.227),
  ('BD20120013','BD2012','ব্রাহ্মণবাড়িয়া সদর','Brahmanbaria Sadar','brahmanbaria-sadar',23.95,91.116),
  ('BD20120063','BD2012','কসবা','Kasba','kasba',23.761,91.131),
  ('BD20120085','BD2012','নবীনগর','Nabinagar','nabinagar',23.863,90.98),
  ('BD20120090','BD2012','নাসিরনগর','Nasirnagar','nasirnagar',24.182,91.187),
  ('BD20120094','BD2012','সরাইল','Sarail','sarail',24.103,91.113),
  ('BD20130022','BD2013','চাঁদপুর সদর','Chandpur Sadar','chandpur-sadar',23.232,90.651),
  ('BD20130045','BD2013','ফরিদগঞ্জ','Faridganj','faridganj',23.144,90.762),
  ('BD20130047','BD2013','হাইমচর','Haimchar','haimchar',23.077,90.617),
  ('BD20130049','BD2013','হাজীগঞ্জ','Hajiganj','hajiganj',23.258,90.837),
  ('BD20130058','BD2013','কচুয়া','Kachua','kachua',23.359,90.883),
  ('BD20130076','BD2013','মতলব দক্ষিণ','Matlab Dakkhin','matlab-dakkhin',23.348,90.747),
  ('BD20130079','BD2013','মতলব উত্তর','Matlab Uttar','matlab-uttar',23.41,90.641),
  ('BD20130095','BD2013','শাহরাস্তি','Shahrasti','shahrasti',23.206,90.957),
  ('BD20150004','BD2015','আনোয়ারা','Anwara','anwara',22.198,91.879),
  ('BD20150008','BD2015','বাঁশখালী','Banshkhali','banshkhali',22.017,91.938),
  ('BD20150012','BD2015','বোয়ালখালী','Boalkhali','boalkhali',22.377,91.966),
  ('BD20150018','BD2015','চন্দনাইশ','Chandanaish','chandanaish',22.212,92.065),
  ('BD20150033','BD2015','ফটিকছড়ি','Fatikchhari','fatikchhari',22.755,91.749),
  ('BD20150037','BD2015','হাটহাজারী','Hathazari','hathazari',22.526,91.798),
  ('BD20150039','BD2015','কর্ণফুলী','Karnaphuli','karnaphuli',22.287,91.846),
  ('BD20150047','BD2015','লোহাগড়া','Lohagara','lohagara',21.986,92.112),
  ('BD20150053','BD2015','সরাইল','Mirsarai','mirsarai',22.804,91.548),
  ('BD20150061','BD2015','পটিয়া','Patiya','patiya',22.293,91.987),
  ('BD20150070','BD2015','রাঙ্গুনিয়া','Rangunia','rangunia',22.466,92.068),
  ('BD20150074','BD2015','রাউজান','Raozan','raozan',22.52,91.917),
  ('BD20150078','BD2015','সন্দ্বীপ','Sandwip','sandwip',22.511,91.458),
  ('BD20150082','BD2015','সাতকানিয়া','Satkania','satkania',22.106,92.06),
  ('BD20150086','BD2015','সীতাকুন্ড','Sitakunda','sitakunda',22.543,91.657),
  ('BD20220016','BD2022','চকরিয়া','Chakaria','chakaria',21.741,92.052),
  ('BD20220024','BD2022','কক্সবাজার সদর','Coxs Bazar Sadar','coxs-bazar-sadar',21.466,92.016),
  ('BD20220032','BD2022','ঈদগাঁও','Eidgaon','eidgaon',21.556,92.059),
  ('BD20220045','BD2022','কুতুবদিয়া','Kutubdia','kutubdia',21.838,91.863),
  ('BD20220049','BD2022','মহেশখালী','Maheshkhali','maheshkhali',21.607,91.92),
  ('BD20220056','BD2022','পেকুয়া','Pekua','pekua',21.816,91.945),
  ('BD20220066','BD2022','রামু','Ramu','ramu',21.439,92.12),
  ('BD20220090','BD2022','টেকনাফ','Teknaf','teknaf',20.969,92.237),
  ('BD20220094','BD2022','উখিয়া','Ukhia','ukhia',21.228,92.115),
  ('BD20190067','BD2019','আদর্শ সদর','Adarsha Sadar','adarsha-sadar',23.48,91.157),
  ('BD20190009','BD2019','বরুড়া','Barura','barura',23.357,91.04),
  ('BD20190015','BD2019','ব্রাহ্মণপাড়া','Brahmanpara','brahmanpara',23.647,91.096),
  ('BD20190018','BD2019','বুড়িচং','Burichang','burichang',23.535,91.117),
  ('BD20190027','BD2019','চান্দিনা','Chandina','chandina',23.446,90.945),
  ('BD20190031','BD2019','চৌদ্দগ্রাম','Chauddagram','chauddagram',23.222,91.28),
  ('BD20190036','BD2019','দাউদকান্দি','Daudkandi','daudkandi',23.503,90.773),
  ('BD20190040','BD2019','দেবিদ্বার','Debidwar','debidwar',23.58,90.998),
  ('BD20190054','BD2019','হোমনা','Homna','homna',23.68,90.811),
  ('BD20190072','BD2019','লাকসাম','Laksam','laksam',23.231,91.105),
  ('BD20190073','BD2019','লালমাই','Lalmai','lalmai',23.298,91.159),
  ('BD20190074','BD2019','মনোহরগঞ্জ','Manoharganj','manoharganj',23.138,91.067),
  ('BD20190075','BD2019','মেঘনা','Meghna','meghna',23.626,90.69),
  ('BD20190081','BD2019','মুরাদনগর','Muradnagar','muradnagar',23.678,90.943),
  ('BD20190087','BD2019','নাঙ্গলকোট','Nangalkot','nangalkot',23.14,91.209),
  ('BD20190033','BD2019','সদর দক্ষিণ','Sadar Dakkhin','sadar-dakkhin',23.388,91.202),
  ('BD20190094','BD2019','তিতাস','Titas','titas',23.591,90.796),
  ('BD20300014','BD2030','ছাগলনাইয়া','Chhagalnaiya','chhagalnaiya',23.02,91.507),
  ('BD20300025','BD2030','দাগনভূঞা','Daganbhuiyan','daganbhuiyan',22.972,91.3),
  ('BD20300029','BD2030','ফেনী সদর','Feni Sadar','feni-sadar',22.991,91.416),
  ('BD20300041','BD2030','ফুলগাজী','Fulgazi','fulgazi',23.118,91.442),
  ('BD20300051','BD2030','পরশুরাম','Parashuram','parashuram',23.202,91.438),
  ('BD20300094','BD2030','সোনাগাজী','Sonagazi','sonagazi',22.854,91.397),
  ('BD20460043','BD2046','দিঘীনালা','Dighinala','dighinala',23.416,92.059),
  ('BD20460047','BD2046','গুইমারা','Guimara','guimara',22.958,91.923),
  ('BD20460049','BD2046','খাগড়াছড়ি সদর','Khagrachhari Sadar','khagrachhari-sadar',23.158,91.998),
  ('BD20460061','BD2046','লক্ষ্মীছড়ি','Lakkhichhari','lakkhichhari',22.784,91.931),
  ('BD20460065','BD2046','মহালছড়ি','Mahalchhari','mahalchhari',22.984,92.049),
  ('BD20460067','BD2046','ফটিকছড়ি','Manikchhari','manikchhari',22.852,91.827),
  ('BD20460070','BD2046','মাটিরাঙ্গা','Matiranga','matiranga',23.163,91.855),
  ('BD20460077','BD2046','পানছড়ি','Panchhari','panchhari',23.342,91.925),
  ('BD20460080','BD2046','রামগড়','Ramgarh','ramgarh',22.954,91.776),
  ('BD20510033','BD2051','কমলনগর','Kamalnagar','kamalnagar',22.757,90.854),
  ('BD20510043','BD2051','লক্ষ্মীপুর সদর','Lakshmipur Sadar','lakshmipur-sadar',22.911,90.844),
  ('BD20510058','BD2051','রায়পুর','Raipur','raipur',23.005,90.732),
  ('BD20510065','BD2051','রামগঞ্জ','Ramganj','ramganj',23.097,90.873),
  ('BD20510073','BD2051','রামগতি','Ramgati','ramgati',22.625,90.922),
  ('BD20750007','BD2075','বেগমগঞ্জ','Begumganj','begumganj',22.931,91.094),
  ('BD20750010','BD2075','চাটখিল','Chatkhil','chatkhil',23.053,90.964),
  ('BD20750021','BD2075','কোম্পানীগঞ্জ','Companiganj','companiganj',22.759,91.301),
  ('BD20750036','BD2075','পটিয়া','Hatiya','hatiya',22.348,91.091),
  ('BD20750047','BD2075','কবিরহাট','Kabirhat','kabirhat',22.811,91.199),
  ('BD20750087','BD2075','নোয়াখালী সদর','Noakhali Sadar','noakhali-sadar',22.808,91.049),
  ('BD20750080','BD2075','সেনবাগ','Senbag','senbag',22.991,91.213),
  ('BD20750083','BD2075','সোনাইমুড়ী','Sonaimuri','sonaimuri',23.026,91.078),
  ('BD20750085','BD2075','সুবর্ণচর','Subarnachar','subarnachar',22.619,91.156),
  ('BD20840007','BD2084','বাঘাইছড়ি','Baghaichhari','baghaichhari',23.383,92.237),
  ('BD20840021','BD2084','বরকল','Barkal','barkal',22.831,92.346),
  ('BD20840029','BD2084','বিলাইছড়ি','Belaichhari','belaichhari',22.257,92.483),
  ('BD20840047','BD2084','জুরাছড়ি','Jurachhari','jurachhari',22.559,92.455),
  ('BD20840036','BD2084','কাপ্তাই','Kaptai','kaptai',22.462,92.202),
  ('BD20840025','BD2084','কাউখালী','Kawkhali','kawkhali',22.623,92.012),
  ('BD20840058','BD2084','লংগদু','Langadu','langadu',22.97,92.217),
  ('BD20840075','BD2084','নানিয়ারচর','Naniarchar','naniarchar',22.834,92.073),
  ('BD20840078','BD2084','রাজস্থলী','Rajasthali','rajasthali',22.372,92.245),
  ('BD20840087','BD2084','রাঙ্গামাটি সদর','Rangamati Sadar','rangamati-sadar',22.645,92.201),
  ('BD30260014','BD3026','ধামরাই','Dhamrai','dhamrai',23.939,90.141),
  ('BD30260018','BD3026','দোহার','Dohar','dohar',23.602,90.108),
  ('BD30260038','BD3026','কেরাণীগঞ্জ','Keraniganj','keraniganj',23.694,90.344),
  ('BD30260062','BD3026','নবাবগঞ্জ','Nawabganj','nawabganj',23.672,90.161),
  ('BD30260072','BD3026','সাভার','Savar','savar',23.88,90.281),
  ('BD30290003','BD3029','আলফাডাঙ্গা','Alfadanga','alfadanga',23.295,89.67),
  ('BD30290010','BD3029','ভাঙ্গা','Bhanga','bhanga',23.389,90.01),
  ('BD30290018','BD3029','বোয়ালমারী','Boalmari','boalmari',23.399,89.692),
  ('BD30290021','BD3029','চরভদ্রাসন','Char Bhadrasan','char-bhadrasan',23.59,89.98),
  ('BD30290047','BD3029','ফরিদপুর সদর','Faridpur Sadar','faridpur-sadar',23.597,89.813),
  ('BD30290056','BD3029','মধুখালী','Madhukhali','madhukhali',23.541,89.611),
  ('BD30290062','BD3029','নগরকান্দা','Nagarkanda','nagarkanda',23.434,89.896),
  ('BD30290084','BD3029','সদরপুর','Sadarpur','sadarpur',23.498,90.051),
  ('BD30290090','BD3029','সালথা','Saltha','saltha',23.418,89.801),
  ('BD30330030','BD3033','গাজীপুর সদর','Gazipur Sadar','gazipur-sadar',24.085,90.425),
  ('BD30330032','BD3033','কালিয়াকৈর','Kaliakair','kaliakair',24.102,90.266),
  ('BD30330034','BD3033','কালীগঞ্জ','Kaliganj','kaliganj',23.965,90.555),
  ('BD30330036','BD3033','কাপাসিয়া','Kapasia','kapasia',24.148,90.6),
  ('BD30330086','BD3033','শ্রীপুর','Sreepur','sreepur',24.206,90.444),
  ('BD30350032','BD3035','গোপালগঞ্জ সদর','Gopalganj Sadar','gopalganj-sadar',23.061,89.848),
  ('BD30350043','BD3035','কাশিয়ানী','Kashiani','kashiani',23.191,89.795),
  ('BD30350051','BD3035','কোটালীপাড়া','Kotalipara','kotalipara',23.011,90.02),
  ('BD30350058','BD3035','মুকসুদপুর','Muksudpur','muksudpur',23.266,89.916),
  ('BD30350091','BD3035','টুংগীপাড়া','Tungipara','tungipara',22.924,89.902),
  ('BD30480002','BD3048','অষ্টগ্রাম','Austagram','austagram',24.324,91.122),
  ('BD30480006','BD3048','বাজিতপুর','Bajitpur','bajitpur',24.227,90.948),
  ('BD30480011','BD3048','ভৈরব','Bhairab','bhairab',24.102,90.981),
  ('BD30480027','BD3048','হোসেনপুর','Hossainpur','hossainpur',24.448,90.663),
  ('BD30480033','BD3048','ইটনা','Itna','itna',24.551,91.084),
  ('BD30480042','BD3048','করিমগঞ্জ','Karimganj','karimganj',24.454,90.896),
  ('BD30480045','BD3048','কটিয়াদী','Katiadi','katiadi',24.295,90.821),
  ('BD30480049','BD3048','কিশোরগঞ্জ সদর','Kishoreganj Sadar','kishoreganj-sadar',24.426,90.783),
  ('BD30480054','BD3048','কুলিয়ারচর','Kuliarchar','kuliarchar',24.153,90.887),
  ('BD30480059','BD3048','মিঠামইন','Mithamain','mithamain',24.433,91.111),
  ('BD30480076','BD3048','নিকলী','Nikli','nikli',24.338,90.961),
  ('BD30480079','BD3048','পাকুন্দিয়া','Pakundia','pakundia',24.321,90.694),
  ('BD30480092','BD3048','তাড়াইল','Tarail','tarail',24.551,90.891),
  ('BD30540018','BD3054','ডাসার','Dasar','dasar',23.092,90.161),
  ('BD30540040','BD3054','কালকিনি','Kalkini','kalkini',23.067,90.281),
  ('BD30540054','BD3054','মাদারীপুর সদর','Madaripur Sadar','madaripur-sadar',23.191,90.178),
  ('BD30540080','BD3054','রাজৈর','Rajoir','rajoir',23.202,90.039),
  ('BD30540087','BD3054','শিবচর','Shibchar','shibchar',23.373,90.176),
  ('BD30560010','BD3056','দৌলতপুর','Daulatpur','daulatpur',23.956,89.799),
  ('BD30560022','BD3056','ঘিওর','Ghior','ghior',23.874,89.904),
  ('BD30560028','BD3056','হরিরামপুর','Harirampur','harirampur',23.721,89.946),
  ('BD30560046','BD3056','মানিকগঞ্জ সদর','Manikganj Sadar','manikganj-sadar',23.837,90.03),
  ('BD30560070','BD3056','সাটুরিয়া','Saturia','saturia',23.958,90.001),
  ('BD30560078','BD3056','শিবালয়','Shibalay','shibalay',23.838,89.811),
  ('BD30560082','BD3056','সিংগাইর','Singair','singair',23.783,90.154),
  ('BD30590024','BD3059','গজারিয়া','Gazaria','gazaria',23.547,90.629),
  ('BD30590044','BD3059','লৌহজং','Louhajang','louhajang',23.469,90.344),
  ('BD30590056','BD3059','মুন্সিগঞ্জ সদর','Munshiganj Sadar','munshiganj-sadar',23.487,90.526),
  ('BD30590074','BD3059','সিরাজদিখান','Sirajdikhan','sirajdikhan',23.598,90.358),
  ('BD30590084','BD3059','শ্রীনগর','Sreenagar','sreenagar',23.546,90.264),
  ('BD30590094','BD3059','টংগীবাড়ি','Tongibari','tongibari',23.475,90.453),
  ('BD30670002','BD3067','আড়াইহাজার','Araihazar','araihazar',23.764,90.669),
  ('BD30670006','BD3067','বন্দর','Bandar','bandar',23.641,90.546),
  ('BD30670058','BD3067','নারায়নগঞ্জ সদর','Narayanganj Sadar','narayanganj-sadar',23.613,90.47),
  ('BD30670068','BD3067','রূপগঞ্জ','Rupganj','rupganj',23.812,90.54),
  ('BD30670004','BD3067','সোনারগাঁ','Sonargaon','sonargaon',23.675,90.594),
  ('BD30680007','BD3068','বেলাবো','Belabo','belabo',24.101,90.849),
  ('BD30680052','BD3068','মনোহরদী','Manohardi','manohardi',24.161,90.731),
  ('BD30680060','BD3068','নরসিংদী সদর','Narsingdi Sadar','narsingdi-sadar',23.869,90.708),
  ('BD30680063','BD3068','পলাশ','Palash','palash',23.956,90.65),
  ('BD30680064','BD3068','রায়পুরা','Raipura','raipura',23.962,90.872),
  ('BD30680076','BD3068','শিবপুর','Shibpur','shibpur',24.028,90.747),
  ('BD30820007','BD3082','বালিয়াকান্দি','Baliakandi','baliakandi',23.651,89.552),
  ('BD30820029','BD3082','গোয়ালন্দ','Goalanda','goalanda',23.756,89.765),
  ('BD30820047','BD3082','কালুখালী','Kalukhali','kalukhali',23.742,89.475),
  ('BD30820073','BD3082','পাংশা','Pangsha','pangsha',23.789,89.388),
  ('BD30820076','BD3082','রাজবাড়ী সদর','Rajbari Sadar','rajbari-sadar',23.717,89.656),
  ('BD30860014','BD3086','ভেদরগঞ্জ','Bhedarganj','bhedarganj',23.248,90.514),
  ('BD30860025','BD3086','ডামুড্যা','Damudya','damudya',23.14,90.423),
  ('BD30860036','BD3086','গোসাইরহাট','Gosairhat','gosairhat',23.082,90.457),
  ('BD30860065','BD3086','নড়িয়া','Naria','naria',23.306,90.428),
  ('BD30860069','BD3086','শরিয়তপুর সদর','Shariatpur Sadar','shariatpur-sadar',23.219,90.317),
  ('BD30860094','BD3086','জাজিরা','Zajira','zajira',23.366,90.324),
  ('BD30930009','BD3093','বাসাইল','Basail','basail',24.234,90.04),
  ('BD30930019','BD3093','ভূঞাপুর','Bhuanpur','bhuanpur',24.477,89.816),
  ('BD30930023','BD3093','দেলদুয়ার','Delduar','delduar',24.148,89.939),
  ('BD30930025','BD3093','ধনবাড়ী','Dhanbari','dhanbari',24.688,89.934),
  ('BD30930028','BD3093','ঘাটাইল','Ghatail','ghatail',24.474,90.053),
  ('BD30930038','BD3093','গোপালপুর','Gopalpur','gopalpur',24.572,89.902),
  ('BD30930047','BD3093','কালিহাতী','Kalihati','kalihati',24.36,89.947),
  ('BD30930057','BD3093','মধুপুর','Madhupur','madhupur',24.65,90.062),
  ('BD30930066','BD3093','মির্জাপুর','Mirzapur','mirzapur',24.118,90.107),
  ('BD30930076','BD3093','নাগরপুর','Nagarpur','nagarpur',24.051,89.875),
  ('BD30930085','BD3093','সখিপুর','Sakhipur','sakhipur',24.306,90.175),
  ('BD30930095','BD3093','টাঙ্গাইল সদর','Tangail Sadar','tangail-sadar',24.26,89.867),
  ('BD40010008','BD4001','বাগেরহাট সদর','Bagerhat Sadar','bagerhat-sadar',22.676,89.763),
  ('BD40010014','BD4001','চিতলমারী','Chitalmari','chitalmari',22.811,89.865),
  ('BD40010034','BD4001','ফকিরহাট','Fakirhat','fakirhat',22.743,89.666),
  ('BD40010038','BD4001','কচুয়া','Kachua','kachua',22.652,89.874),
  ('BD40010056','BD4001','মোল্লাহাট','Mollahat','mollahat',22.884,89.773),
  ('BD40010058','BD4001','মোংলা','Mongla','mongla',22.117,89.66),
  ('BD40010060','BD4001','মোড়েলগঞ্জ','Morelganj','morelganj',22.483,89.834),
  ('BD40010073','BD4001','রামপাল','Rampal','rampal',22.59,89.651),
  ('BD40010077','BD4001','শরণখোলা','Sharankhola','sharankhola',22.063,89.822),
  ('BD40180007','BD4018','আলমডাঙ্গা','Alamdanga','alamdanga',23.73,88.908),
  ('BD40180023','BD4018','চুয়াডাঙ্গা সদর','Chuadanga Sadar','chuadanga-sadar',23.589,88.885),
  ('BD40180031','BD4018','দামুড়হুদা','Damurhuda','damurhuda',23.592,88.74),
  ('BD40180055','BD4018','জীবননগর','Jibannagar','jibannagar',23.443,88.85),
  ('BD40410004','BD4041','অভয়নগর','Abhaynagar','abhaynagar',23.018,89.42),
  ('BD40410009','BD4041','বাঘারপাড়া','Bagharpara','bagharpara',23.243,89.335),
  ('BD40410011','BD4041','চৌগাছা','Chaugachha','chaugachha',23.263,89.023),
  ('BD40410047','BD4041','নাটোর সদর','Jashore Sadar','jashore-sadar',23.182,89.219),
  ('BD40410023','BD4041','ঝিকরগাছা','Jhikargachha','jhikargachha',23.069,89.054),
  ('BD40410038','BD4041','কেশবপুর','Keshabpur','keshabpur',22.88,89.232),
  ('BD40410061','BD4041','মণিরামপুর','Manirampur','manirampur',23.006,89.22),
  ('BD40410090','BD4041','শার্শা','Sharsha','sharsha',23.045,88.941),
  ('BD40440014','BD4044','হরিণাকুন্ডু','Harinakundu','harinakundu',23.644,89.077),
  ('BD40440019','BD4044','ঝিনাইদহ সদর','Jhenaidah Sadar','jhenaidah-sadar',23.516,89.158),
  ('BD40440033','BD4044','কালীগঞ্জ','Kaliganj','kaliganj',23.37,89.152),
  ('BD40440042','BD4044','কোটচাঁদপুর','Kotchandpur','kotchandpur',23.445,89.001),
  ('BD40440071','BD4044','মহেশপুর','Maheshpur','maheshpur',23.32,88.86),
  ('BD40440080','BD4044','শৈলকুপা','Shailkupa','shailkupa',23.664,89.243),
  ('BD40470012','BD4047','বটিয়াঘাটা','Batiaghata','batiaghata',22.713,89.515),
  ('BD40470017','BD4047','দাকোপ','Dacope','dacope',22.242,89.526),
  ('BD40470040','BD4047','কাঠালিয়া','Dighalia','dighalia',22.922,89.554),
  ('BD40470030','BD4047','ডুমুরিয়া','Dumuria','dumuria',22.806,89.398),
  ('BD40470053','BD4047','কয়রা','Koyra','koyra',22.078,89.395),
  ('BD40470064','BD4047','চৌগাছা','Paikgachha','paikgachha',22.59,89.34),
  ('BD40470069','BD4047','ফুলতলা','Phultala','phultala',22.948,89.454),
  ('BD40470075','BD4047','রূপসা','Rupsa','rupsa',22.819,89.636),
  ('BD40470094','BD4047','তেরখাদা','Terokhada','terokhada',22.914,89.655),
  ('BD40500015','BD4050','ভেড়ামারা','Bheramara','bheramara',24.056,88.981),
  ('BD40500039','BD4050','দৌলতপুর','Daulatpur','daulatpur',24.034,88.836),
  ('BD40500063','BD4050','খোকসা','Khoksa','khoksa',23.811,89.3),
  ('BD40500071','BD4050','কুমারখালী','Kumarkhali','kumarkhali',23.858,89.21),
  ('BD40500079','BD4050','কুষ্টিয়া সদর','Kushtia Sadar','kushtia-sadar',23.824,89.09),
  ('BD40500094','BD4050','মিরপুর','Mirpur','mirpur',23.897,88.986),
  ('BD40550057','BD4055','মাগুরা সদর','Magura Sadar','magura-sadar',23.452,89.412),
  ('BD40550066','BD4055','মহম্মদপুর','Mohammadpur','mohammadpur',23.4,89.551),
  ('BD40550085','BD4055','শালিখা','Shalikha','shalikha',23.348,89.359),
  ('BD40550095','BD4055','শ্রীপুর','Sreepur','sreepur',23.598,89.424),
  ('BD40570047','BD4057','গাংনী','Gangni','gangni',23.857,88.771),
  ('BD40570087','BD4057','মেহেরপুর সদর','Meherpur Sadar','meherpur-sadar',23.765,88.661),
  ('BD40570060','BD4057','মুজিবনগর','Mujibnagar','mujibnagar',23.668,88.621),
  ('BD40650028','BD4065','কালিয়া','Kalia','kalia',23.029,89.642),
  ('BD40650052','BD4065','লোহাগড়া','Lohagara','lohagara',23.204,89.624),
  ('BD40650076','BD4065','নড়াইল সদর','Narail Sadar','narail-sadar',23.155,89.495),
  ('BD40870004','BD4087','আশাশুনি','Ashashuni','ashashuni',22.519,89.187),
  ('BD40870025','BD4087','দেবহাটা','Debhata','debhata',22.597,89.013),
  ('BD40870043','BD4087','কলারোয়া','Kalaroa','kalaroa',22.88,89.03),
  ('BD40870047','BD4087','কালীগঞ্জ','Kaliganj','kaliganj',22.447,89.062),
  ('BD40870082','BD4087','সাতক্ষীরা সদর','Satkhira Sadar','satkhira-sadar',22.72,89.038),
  ('BD40870086','BD4087','শ্যামনগর','Shyamnagar','shyamnagar',22.012,89.181),
  ('BD40870090','BD4087','তালা','Tala','tala',22.74,89.211),
  ('BD50100006','BD5010','আদমদিঘি','Adamdighi','adamdighi',24.8,89.06),
  ('BD50100020','BD5010','মাগুরা সদর','Bogura Sadar','bogura-sadar',24.895,89.356),
  ('BD50100027','BD5010','ধুনট','Dhunat','dhunat',24.683,89.55),
  ('BD50100033','BD5010','দুপচাঁচিয়া','Dupchachia','dupchachia',24.882,89.14),
  ('BD50100040','BD5010','গাবতলী','Gabtali','gabtali',24.887,89.465),
  ('BD50100054','BD5010','কাহালু','Kahaloo','kahaloo',24.833,89.251),
  ('BD50100067','BD5010','নন্দিগ্রাম','Nandigram','nandigram',24.681,89.227),
  ('BD50100081','BD5010','সারিয়াকান্দি','Sariakandi','sariakandi',24.879,89.617),
  ('BD50100085','BD5010','শাজাহানপুর','Shajahanpur','shajahanpur',24.76,89.376),
  ('BD50100088','BD5010','শেরপুর','Sherpur','sherpur',24.629,89.423),
  ('BD50100094','BD5010','শিবগঞ্জ','Shibganj','shibganj',25.017,89.306),
  ('BD50100095','BD5010','সোনাতলা','Sonatala','sonatala',24.997,89.514),
  ('BD50700018','BD5070','ভোলাহাট','Bholahat','bholahat',24.897,88.209),
  ('BD50700066','BD5070','চাঁপাইনবাবগঞ্জ সদর','Chapainawabganj Sadar','chapainawabganj-sadar',24.565,88.258),
  ('BD50700037','BD5070','গোমস্তাপুর','Gomastapur','gomastapur',24.859,88.355),
  ('BD50700056','BD5070','নাচোল','Nachole','nachole',24.727,88.396),
  ('BD50700088','BD5070','শিবগঞ্জ','Shibganj','shibganj',24.705,88.155),
  ('BD50380013','BD5038','আক্কেলপুর','Akkelpur','akkelpur',24.933,89.042),
  ('BD50380047','BD5038','জয়পুরহাট সদর','Joypurhat Sadar','joypurhat-sadar',25.108,89.021),
  ('BD50380058','BD5038','কালাই','Kalai','kalai',25.078,89.199),
  ('BD50380061','BD5038','ক্ষেতলাল','Khetlal','khetlal',25.023,89.118),
  ('BD50380074','BD5038','পাঁচবিবি','Panchbibi','panchbibi',25.205,89.072),
  ('BD50640003','BD5064','আত্রাই','Atrai','atrai',24.625,88.989),
  ('BD50640006','BD5064','বদলগাছী','Badalgachhi','badalgachhi',24.967,88.943),
  ('BD50640028','BD5064','ধামইরহাট','Dhamoirhat','dhamoirhat',25.131,88.824),
  ('BD50640050','BD5064','মহাদেবপুর','Mahadebpur','mahadebpur',24.922,88.764),
  ('BD50640047','BD5064','মান্দা','Manda','manda',24.746,88.712),
  ('BD50640060','BD5064','নওগাঁ সদর','Naogaon Sadar','naogaon-sadar',24.812,88.898),
  ('BD50640069','BD5064','নিয়ামতপুর','Niamatpur','niamatpur',24.83,88.55),
  ('BD50640075','BD5064','পত্নিতলা','Patnitala','patnitala',25.078,88.715),
  ('BD50640079','BD5064','পোরশা','Porsha','porsha',24.995,88.517),
  ('BD50640085','BD5064','রাণীনগর','Raninagar','raninagar',24.712,89.02),
  ('BD50640086','BD5064','সাপাহার','Sapahar','sapahar',25.119,88.531),
  ('BD50690009','BD5069','বাগাতিপাড়া','Bagatipara','bagatipara',24.313,88.948),
  ('BD50690015','BD5069','বড়াইগ্রাম','Baraigram','baraigram',24.273,89.15),
  ('BD50690041','BD5069','গুরুদাসপুর','Gurudaspur','gurudaspur',24.374,89.205),
  ('BD50690044','BD5069','লালপুর','Lalpur','lalpur',24.2,88.986),
  ('BD50690055','BD5069','নলডাঙ্গা','Naldanga','naldanga',24.506,88.976),
  ('BD50690063','BD5069','নাটোর সদর','Natore Sadar','natore-sadar',24.397,88.99),
  ('BD50690091','BD5069','সিংড়া','Singra','singra',24.524,89.184),
  ('BD50760005','BD5076','আটঘরিয়া','Atgharia','atgharia',24.107,89.283),
  ('BD50760016','BD5076','বেড়া','Bera','bera',23.943,89.657),
  ('BD50760019','BD5076','ভাঙ্গুড়া','Bhangura','bhangura',24.239,89.396),
  ('BD50760022','BD5076','চাটমোহর','Chatmohar','chatmohar',24.224,89.303),
  ('BD50760033','BD5076','ফরিদপুর','Faridpur','faridpur',24.158,89.449),
  ('BD50760039','BD5076','ঈশ্বরদী','Ishwardi','ishwardi',24.08,89.094),
  ('BD50760055','BD5076','পাবনা সদর','Pabna Sadar','pabna-sadar',23.995,89.281),
  ('BD50760072','BD5076','সাঁথিয়া','Santhia','santhia',24.043,89.516),
  ('BD50760083','BD5076','সুজানগর','Sujanagar','sujanagar',23.898,89.514),
  ('BD50810010','BD5081','বাঘা','Bagha','bagha',24.206,88.834),
  ('BD50810012','BD5081','বাগমারা','Bagmara','bagmara',24.594,88.809),
  ('BD50810025','BD5081','চারঘাট','Charghat','charghat',24.301,88.775),
  ('BD50810031','BD5081','দুর্গাপুর','Durgapur','durgapur',24.468,88.761),
  ('BD50810034','BD5081','গোদাগাড়ী','Godagari','godagari',24.483,88.415),
  ('BD50810053','BD5081','লালমোহন','Mohanpur','mohanpur',24.555,88.641),
  ('BD50810072','BD5081','পবা','Paba','paba',24.338,88.591),
  ('BD50810082','BD5081','পুঠিয়া','Puthia','puthia',24.411,88.827),
  ('BD50810094','BD5081','তানোর','Tanore','tanore',24.62,88.531),
  ('BD50880011','BD5088','বেলকুচি','Belkuchi','belkuchi',24.298,89.701),
  ('BD50880027','BD5088','চৌহালি','Chouhali','chouhali',24.139,89.757),
  ('BD50880044','BD5088','কামারখন্দ','Kamarkhanda','kamarkhanda',24.378,89.642),
  ('BD50880050','BD5088','কাজীপুর','Kazipur','kazipur',24.672,89.689),
  ('BD50880061','BD5088','রায়গঞ্জ','Rayganj','rayganj',24.492,89.515),
  ('BD50880067','BD5088','শাহজাদপুর','Shahjadpur','shahjadpur',24.163,89.631),
  ('BD50880078','BD5088','সিরাজগঞ্জ সদর','Sirajganj Sadar','sirajganj-sadar',24.494,89.69),
  ('BD50880089','BD5088','তাড়াশ','Tarash','tarash',24.445,89.358),
  ('BD50880094','BD5088','উল্লাপাড়া','Ullapara','ullapara',24.328,89.518),
  ('BD10040009','BD1004','আমতলী','Amtali','amtali',22.147,90.27),
  ('BD10040019','BD1004','বামনা','Bamna','bamna',22.272,90.057),
  ('BD10040028','BD1004','বরগুনা সদর','Barguna Sadar','barguna-sadar',22.127,90.102),
  ('BD10040047','BD1004','বেতাগী','Betagi','betagi',22.348,90.149),
  ('BD10040085','BD1004','চারঘাট','Patharghata','patharghata',22.09,89.959),
  ('BD10040090','BD1004','তালতলি','Taltali','taltali',21.968,90.101),
  ('BD10060002','BD1006','আগৈলঝাড়া','Agailjhara','agailjhara',22.968,90.14),
  ('BD10060003','BD1006','বাবুগঞ্জ','Babuganj','babuganj',22.825,90.313),
  ('BD10060007','BD1006','বাকেরগঞ্জ','Bakerganj','bakerganj',22.555,90.39),
  ('BD10060010','BD1006','বানারীপাড়া','Banaripara','banaripara',22.811,90.129),
  ('BD10060051','BD1006','বরিশাল সদর (কোতোয়ালি)','Barishal Sadar (Kotwali)','barishal-sadar-kotwali',22.715,90.41),
  ('BD10060032','BD1006','গৌরনদী','Gaurnadi','gaurnadi',22.97,90.243),
  ('BD10060036','BD1006','হিজলা','Hijla','hijla',22.963,90.552),
  ('BD10060062','BD1006','মেহেন্দিগঞ্জ','Mehendiganj','mehendiganj',22.816,90.519),
  ('BD10060069','BD1006','মুলাদী','Muladi','muladi',22.955,90.376),
  ('BD10060094','BD1006','মিরপুর','Ujirpur','ujirpur',22.866,90.165),
  ('BD10090018','BD1009','ভোলা সদর','Bhola Sadar','bhola-sadar',22.707,90.631),
  ('BD10090021','BD1009','বোরহানউদ্দিন','Borhanuddin','borhanuddin',22.485,90.715),
  ('BD10090025','BD1009','চরফ্যাশন','Charfasson','charfasson',22.045,90.725),
  ('BD10090029','BD1009','দৌলতখান','Daulatkhan','daulatkhan',22.642,90.745),
  ('BD10090054','BD1009','লালমোহন','Lalmohan','lalmohan',22.302,90.771),
  ('BD10090065','BD1009','মনপুরা','Monpura','monpura',22.222,90.943),
  ('BD10090091','BD1009','তজুমদ্দিন','Tazumuddin','tazumuddin',22.453,90.86),
  ('BD10420040','BD1042','ঝালকাঠি সদর','Jhalokathi Sadar','jhalokathi-sadar',22.68,90.193),
  ('BD10420043','BD1042','কাঠালিয়া','Kanthalia','kanthalia',22.419,90.102),
  ('BD10420073','BD1042','নলছিটি','Nalchhity','nalchhity',22.601,90.271),
  ('BD10420084','BD1042','রাজাপুর','Rajapur','rajapur',22.55,90.131),
  ('BD10780038','BD1078','বাউফল','Bauphal','bauphal',22.437,90.546),
  ('BD10780052','BD1078','দশমিনা','Dashmina','dashmina',22.251,90.554),
  ('BD10780055','BD1078','দুমকি','Dumki','dumki',22.448,90.373),
  ('BD10780057','BD1078','গলাচিপা','Galachipa','galachipa',22.148,90.461),
  ('BD10780066','BD1078','কলাপাড়া','Kalapara','kalapara',21.934,90.222),
  ('BD10780076','BD1078','মির্জাগঞ্জ','Mirzaganj','mirzaganj',22.356,90.217),
  ('BD10780095','BD1078','পটুয়াখালী সদর','Patuakhali Sadar','patuakhali-sadar',22.335,90.329),
  ('BD10780097','BD1078','রাঙ্গাবালী','Rangabali','rangabali',21.932,90.43),
  ('BD10790014','BD1079','ভান্ডারিয়া','Bhandaria','bhandaria',22.452,90.02),
  ('BD10790090','BD1079','ইন্দুরকানী','Indurkani','indurkani',22.466,89.965),
  ('BD10790047','BD1079','কাউখালী','Kawkhali','kawkhali',22.606,90.057),
  ('BD10790058','BD1079','মঠবাড়ীয়া','Mathbaria','mathbaria',22.283,89.949),
  ('BD10790076','BD1079','নাজিরপুর','Nazirpur','nazirpur',22.77,89.975),
  ('BD10790087','BD1079','নেছারাবাদ (স্বরূপকাঠি)','Nesarabad (Swarupkathi)','nesarabad-swarupkathi',22.721,90.086),
  ('BD10790080','BD1079','পিরোজপুর সদর','Pirojpur Sadar','pirojpur-sadar',22.609,89.979),
  ('BD45390007','BD4539','বকশীগঞ্জ','Bakshiganj','bakshiganj',25.214,89.852),
  ('BD45390015','BD4539','দেওয়ানগঞ্জ','Dewanganj','dewanganj',25.268,89.766),
  ('BD45390029','BD4539','ইসলামপুর','Islampur','islampur',25.076,89.763),
  ('BD45390036','BD4539','জামালপুর সদর','Jamalpur Sadar','jamalpur-sadar',24.843,90.015),
  ('BD45390058','BD4539','মাদারগঞ্জ','Madarganj','madarganj',24.885,89.742),
  ('BD45390061','BD4539','মেলান্দহ','Melandaha','melandaha',24.956,89.828),
  ('BD45390085','BD4539','সরিষাবাড়ী','Sarishabari','sarishabari',24.722,89.831),
  ('BD45610013','BD4561','ভালুকা','Bhaluka','bhaluka',24.382,90.354),
  ('BD45610016','BD4561','ধোবাউড়া','Dhobaura','dhobaura',25.101,90.526),
  ('BD45610020','BD4561','ফুলবাড়ীয়া','Fulbaria','fulbaria',24.587,90.256),
  ('BD45610081','BD4561','ফুলপুর','Fulpur','fulpur',24.953,90.353),
  ('BD45610022','BD4561','গফরগাঁও','Gafargaon','gafargaon',24.394,90.55),
  ('BD45610023','BD4561','গৌরীপুর','Gouripur','gouripur',24.757,90.586),
  ('BD45610024','BD4561','হালুয়াঘাট','Haluaghat','haluaghat',25.084,90.352),
  ('BD45610031','BD4561','ঈশ্বরগঞ্জ','Ishwarganj','ishwarganj',24.645,90.6),
  ('BD45610065','BD4561','মুক্তাগাছা','Muktagachha','muktagachha',24.744,90.206),
  ('BD45610052','BD4561','ময়মনসিংহ সদর','Mymensingh Sadar','mymensingh-sadar',24.846,90.264),
  ('BD45610072','BD4561','নান্দাইল','Nandail','nandail',24.549,90.677),
  ('BD45610088','BD4561','তারাকান্দা','Tarakanda','tarakanda',24.864,90.463),
  ('BD45610094','BD4561','ত্রিশাল','Trishal','trishal',24.564,90.41),
  ('BD45720004','BD4572','আটপাড়া','Atpara','atpara',24.794,90.877),
  ('BD45720009','BD4572','বারহাট্টা','Barhatta','barhatta',24.922,90.885),
  ('BD45720018','BD4572','দুর্গাপুর','Durgapur','durgapur',25.089,90.683),
  ('BD45720040','BD4572','কলমাকান্দা','Kalmakanda','kalmakanda',25.078,90.858),
  ('BD45720047','BD4572','কেন্দুয়া','Kendua','kendua',24.678,90.802),
  ('BD45720038','BD4572','খালিয়াজুরী','Khaliajuri','khaliajuri',24.705,91.122),
  ('BD45720056','BD4572','মদন','Madan','madan',24.678,90.967),
  ('BD45720063','BD4572','মোহনগঞ্জ','Mohanganj','mohanganj',24.828,91.023),
  ('BD45720074','BD4572','নেত্রকোণা সদর','Netrakona Sadar','netrakona-sadar',24.887,90.738),
  ('BD45720083','BD4572','পূর্বধলা','Purbadhala','purbadhala',24.934,90.603),
  ('BD45890037','BD4589','ঝিনাইগাতী','Jhenaigati','jhenaigati',25.182,90.054),
  ('BD45890067','BD4589','নকলা','Nakla','nakla',24.958,90.185),
  ('BD45890070','BD4589','নালিতাবাড়ী','Nalitabari','nalitabari',25.117,90.184),
  ('BD45890088','BD4589','শেরপুর সদর','Sherpur Sadar','sherpur-sadar',24.991,90.022),
  ('BD45890090','BD4589','শ্রীবরদী','Sreebardi','sreebardi',25.165,89.957),
  ('BD55270010','BD5527','বিরামপুর','Birampur','birampur',25.38,88.963),
  ('BD55270012','BD5527','বীরগঞ্জ','Birganj','birganj',25.929,88.626),
  ('BD55270017','BD5527','বিরল','Birol','birol',25.647,88.547),
  ('BD55270021','BD5527','বোচাগঞ্জ','Bochaganj','bochaganj',25.786,88.453),
  ('BD55270030','BD5527','চিরিরবন্দর','Chirirbandar','chirirbandar',25.667,88.783),
  ('BD55270064','BD5527','দিনাজপুর সদর','Dinajpur Sadar','dinajpur-sadar',25.608,88.676),
  ('BD55270038','BD5527','ফুলবাড়ী','Fulbari','fulbari',25.471,88.901),
  ('BD55270043','BD5527','ঘোড়াঘাট','Ghoraghat','ghoraghat',25.287,89.215),
  ('BD55270047','BD5527','হাকিমপুর','Hakimpur','hakimpur',25.293,89.061),
  ('BD55270056','BD5527','কাহারোল','Kaharole','kaharole',25.802,88.599),
  ('BD55270060','BD5527','খানসামা','Khansama','khansama',25.872,88.765),
  ('BD55270069','BD5527','নবাবগঞ্জ','Nababganj','nababganj',25.421,89.091),
  ('BD55270077','BD5527','পার্বতীপুর','Parbatipur','parbatipur',25.62,88.923),
  ('BD55320021','BD5532','ফুলছড়ি','Fulchhari','fulchhari',25.254,89.653),
  ('BD55320024','BD5532','গাইবান্ধা সদর','Gaibandha Sadar','gaibandha-sadar',25.35,89.566),
  ('BD55320030','BD5532','গোবিন্দগঞ্জ','Gobindaganj','gobindaganj',25.158,89.37),
  ('BD55320067','BD5532','পলাশবাড়ী','Palashbari','palashbari',25.265,89.392),
  ('BD55320082','BD5532','সাদুল্লাপুর','Sadullapur','sadullapur',25.395,89.426),
  ('BD55320088','BD5532','সাঘাটা','Saghata','saghata',25.125,89.563),
  ('BD55320091','BD5532','সুন্দরগঞ্জ','Sundarganj','sundarganj',25.51,89.562),
  ('BD55490006','BD5549','ভুরুঙ্গামারী','Bhurungamari','bhurungamari',26.116,89.693),
  ('BD55490009','BD5549','চিলমারী','Chilmari','chilmari',25.564,89.718),
  ('BD55490052','BD5549','কুড়িগ্রাম সদর','Kurigram Sadar','kurigram-sadar',25.827,89.691),
  ('BD55490061','BD5549','নাগেশ্বরী','Nageshwari','nageshwari',25.96,89.74),
  ('BD55490018','BD5549','ফুলবাড়ী','Phulbari','phulbari',25.948,89.572),
  ('BD55490077','BD5549','রাজারহাট','Rajarhat','rajarhat',25.787,89.542),
  ('BD55490008','BD5549','চর রাজিবপুর','Rajibpur','rajibpur',25.444,89.764),
  ('BD55490079','BD5549','রৌমারী','Roumari','roumari',25.593,89.828),
  ('BD55490094','BD5549','উলিপুর','Ulipur','ulipur',25.69,89.669),
  ('BD55520002','BD5552','আদিতমারী','Aditmari','aditmari',25.943,89.368),
  ('BD55520033','BD5552','হাতীবান্ধা','Hatibandha','hatibandha',26.12,89.144),
  ('BD55520039','BD5552','কালীগঞ্জ','Kaliganj','kaliganj',25.986,89.242),
  ('BD55520055','BD5552','লালমনিরহাট সদর','Lalmonirhat Sadar','lalmonirhat-sadar',25.879,89.453),
  ('BD55520070','BD5552','পাটগ্রাম','Patgram','patgram',26.343,89.02),
  ('BD55730012','BD5573','ডিমলা','Dimla','dimla',26.173,88.974),
  ('BD55730015','BD5573','ডোমার','Domar','domar',26.16,88.825),
  ('BD55730036','BD5573','জলঢাকা','Jaldhaka','jaldhaka',26.031,88.994),
  ('BD55730045','BD5573','কিশোরগঞ্জ সদর','Kishoreganj','kishoreganj',25.898,89.033),
  ('BD55730064','BD5573','নীলফামারী সদর','Nilphamari Sadar','nilphamari-sadar',25.942,88.855),
  ('BD55730085','BD5573','ফরিদপুর','Saidpur','saidpur',25.804,88.921),
  ('BD55770004','BD5577','আটোয়ারী','Atowari','atowari',26.251,88.425),
  ('BD55770025','BD5577','বোদা','Boda','boda',26.235,88.619),
  ('BD55770034','BD5577','দেবীগঞ্জ','Debiganj','debiganj',26.127,88.717),
  ('BD55770073','BD5577','পঞ্চগড় সদর','Panchagarh Sadar','panchagarh-sadar',26.365,88.591),
  ('BD55770090','BD5577','তেতুলিয়া','Tetulia','tetulia',26.513,88.431),
  ('BD55850003','BD5585','মাদারগঞ্জ','Badarganj','badarganj',25.668,89.055),
  ('BD55850027','BD5585','গংগাচড়া','Gangachara','gangachara',25.88,89.201),
  ('BD55850042','BD5585','কাউনিয়া','Kaunia','kaunia',25.766,89.394),
  ('BD55850058','BD5585','মিঠাপুকুর','Mithapukur','mithapukur',25.572,89.261),
  ('BD55850073','BD5585','পীরগাছা','Pirgachha','pirgachha',25.665,89.422),
  ('BD55850076','BD5585','পীরগঞ্জ','Pirganj','pirganj',25.426,89.275),
  ('BD55850049','BD5585','রংপুর সদর','Rangpur Sadar','rangpur-sadar',25.751,89.151),
  ('BD55850092','BD5585','বালাগঞ্জ','Taraganj','taraganj',25.783,89.033),
  ('BD55940008','BD5594','বালিয়াডাঙ্গী','Baliadangi','baliadangi',26.108,88.263),
  ('BD55940051','BD5594','হরিপুর','Haripur','haripur',25.879,88.155),
  ('BD55940082','BD5594','পীরগঞ্জ','Pirganj','pirganj',25.842,88.368),
  ('BD55940086','BD5594','রাণীশংকৈল','Ranishankail','ranishankail',25.941,88.246),
  ('BD55940094','BD5594','ঠাকুরগাঁও সদর','Thakurgaon Sadar','thakurgaon-sadar',26.072,88.464),
  ('BD60360002','BD6036','আজমিরীগঞ্জ','Ajmiriganj','ajmiriganj',24.554,91.281),
  ('BD60360005','BD6036','বাহুবল','Bahubal','bahubal',24.361,91.545),
  ('BD60360011','BD6036','বানিয়াচং','Baniachong','baniachong',24.499,91.367),
  ('BD60360026','BD6036','চুনারুঘাট','Chunarughat','chunarughat',24.18,91.516),
  ('BD60360044','BD6036','হবিগঞ্জ সদর','Habiganj Sadar','habiganj-sadar',24.351,91.416),
  ('BD60360068','BD6036','লাখাই','Lakhai','lakhai',24.299,91.261),
  ('BD60360071','BD6036','মাধবপুর','Madhabpur','madhabpur',24.12,91.337),
  ('BD60360077','BD6036','নবীগঞ্জ','Nabiganj','nabiganj',24.571,91.548),
  ('BD60360087','BD6036','শায়েস্তাগঞ্জ','Shayestaganj','shayestaganj',24.275,91.407),
  ('BD60580014','BD6058','বড়লেখা','Baralekha','baralekha',24.709,92.176),
  ('BD60580035','BD6058','জুড়ী','Juri','juri',24.554,92.145),
  ('BD60580056','BD6058','জামালগঞ্জ','Kamalganj','kamalganj',24.317,91.86),
  ('BD60580065','BD6058','কুলাউড়া','Kulaura','kulaura',24.49,92.015),
  ('BD60580074','BD6058','মৌলভীবাজার সদর','Moulvibazar Sadar','moulvibazar-sadar',24.499,91.713),
  ('BD60580080','BD6058','রাজনগর','Rajnagar','rajnagar',24.565,91.864),
  ('BD60580083','BD6058','শ্রীমঙ্গল','Sreemangal','sreemangal',24.302,91.699),
  ('BD60900018','BD6090','বিশ্বম্ভরপুর','Bishwambharpur','bishwambharpur',25.109,91.315),
  ('BD60900023','BD6090','ছাতক','Chhatak','chhatak',24.949,91.615),
  ('BD60900029','BD6090','দিরাই','Derai','derai',24.787,91.336),
  ('BD60900032','BD6090','ধর্মপাশা','Dharmapasha','dharmapasha',24.944,91.064),
  ('BD60900033','BD6090','দোয়ারাবাজার','Dowarabazar','dowarabazar',25.072,91.561),
  ('BD60900047','BD6090','জগন্নাথপুর','Jagannathpur','jagannathpur',24.75,91.557),
  ('BD60900050','BD6090','জামালগঞ্জ','Jamalganj','jamalganj',24.956,91.203),
  ('BD60900063','BD6090','মধ্যনগর','Madhyanagar','madhyanagar',25.09,91.013),
  ('BD60900086','BD6090','শাল্লা','Shalla','shalla',24.687,91.259),
  ('BD60900087','BD6090','শান্তিগঞ্জ','Shantiganj','shantiganj',24.912,91.408),
  ('BD60900089','BD6090','সুনামগঞ্জ সদর','Sunamganj Sadar','sunamganj-sadar',25.054,91.4),
  ('BD60900092','BD6090','তাহিরপুর','Tahirpur','tahirpur',25.129,91.164),
  ('BD60910008','BD6091','বালাগঞ্জ','Balaganj','balaganj',24.689,91.83),
  ('BD60910017','BD6091','বিয়ানীবাজার','Beanibazar','beanibazar',24.849,92.16),
  ('BD60910020','BD6091','বিশ্বনাথ','Bishwanath','bishwanath',24.835,91.728),
  ('BD60910027','BD6091','কোম্পানীগঞ্জ','Companiganj','companiganj',25.08,91.773),
  ('BD60910031','BD6091','দক্ষিণ সুরমা','Dakkhin Surma','dakkhin-surma',24.817,91.877),
  ('BD60910035','BD6091','ফেঞ্চুগঞ্জ','Fenchuganj','fenchuganj',24.694,91.963),
  ('BD60910038','BD6091','গোলাপগঞ্জ','Golapganj','golapganj',24.81,92.018),
  ('BD60910041','BD6091','গোয়াইনঘাট','Gowainghat','gowainghat',25.081,91.959),
  ('BD60910053','BD6091','জৈন্তাপুর','Jaintapur','jaintapur',25.058,92.105),
  ('BD60910059','BD6091','কানাইঘাট','Kanaighat','kanaighat',24.993,92.219),
  ('BD60910060','BD6091','ওসমানী নগর','Osmaninagar','osmaninagar',24.703,91.732),
  ('BD60910062','BD6091','সিলেট সদর','Sylhet Sadar','sylhet-sadar',24.944,91.846),
  ('BD60910094','BD6091','জকিগঞ্জ','Zakiganj','zakiganj',24.925,92.368)
)
insert into public.upazilas(
  source_code,district_id,name_bn,name_en,slug,latitude,longitude,is_active
)
select i.source_code,d.id,i.name_bn,i.name_en,i.slug,i.latitude,i.longitude,true
from incoming i
join public.districts d on d.source_code=i.district_code
on conflict(district_id,slug) do update
set source_code=excluded.source_code,name_bn=excluded.name_bn,name_en=excluded.name_en,
    latitude=excluded.latitude,longitude=excluded.longitude,is_active=true;

-- ------------------------------------------------------------
-- SPECIALTY + PATIENT-FRIENDLY DISCOVERY TOPIC SEED
-- ------------------------------------------------------------
insert into public.specialties(name_bn,name_en,slug,sort_order,is_active)
values
  ('মেডিসিন','Internal Medicine','medicine',10,true),
  ('হৃদরোগ','Cardiology','cardiology',20,true),
  ('স্নায়ুরোগ','Neurology','neurology',30,true),
  ('চক্ষুরোগ','Ophthalmology','ophthalmology',40,true),
  ('নাক-কান-গলা','ENT','ent',50,true),
  ('দন্তরোগ','Dentistry','dentistry',60,true),
  ('অর্থোপেডিকস','Orthopedics','orthopedics',70,true),
  ('শিশুরোগ','Pediatrics','pediatrics',80,true),
  ('স্ত্রী ও প্রসূতিরোগ','Gynecology & Obstetrics','gynecology-obstetrics',90,true),
  ('চর্ম ও যৌনরোগ','Dermatology','dermatology',100,true),
  ('মানসিক রোগ','Psychiatry','psychiatry',110,true),
  ('পরিপাকতন্ত্র ও লিভার','Gastroenterology','gastroenterology',120,true),
  ('কিডনি রোগ','Nephrology','nephrology',130,true),
  ('মূত্ররোগ','Urology','urology',140,true),
  ('বক্ষব্যাধি','Pulmonology','pulmonology',150,true),
  ('হরমোন ও ডায়াবেটিস','Endocrinology & Diabetes','endocrinology-diabetes',160,true),
  ('জেনারেল সার্জারি','General Surgery','general-surgery',170,true),
  ('নিউরোসার্জারি','Neurosurgery','neurosurgery',180,true),
  ('ক্যান্সার','Oncology','oncology',190,true),
  ('বাত ও জয়েন্ট','Rheumatology','rheumatology',200,true),
  ('রক্তরোগ','Hematology','hematology',210,true),
  ('অ্যানেস্থেসিওলজি','Anesthesiology','anesthesiology',220,true),
  ('রেডিওলজি ও ইমেজিং','Radiology & Imaging','radiology-imaging',230,true),
  ('প্যাথলজি','Pathology','pathology',240,true),
  ('ফিজিওথেরাপি','Physiotherapy','physiotherapy',250,true),
  ('পুষ্টি','Nutrition','nutrition',260,true)
on conflict(slug) do update
set name_bn=excluded.name_bn,name_en=excluded.name_en,
    sort_order=excluded.sort_order,is_active=true;

insert into public.discovery_topics(
  name_bn,name_en,slug,icon,search_keywords,sort_order,is_active
)
values
  ('হৃদরোগ','Heart','heart',null,array['হার্ট','হৃদপিণ্ড','বুক ধড়ফড়','cardiac']::text[],10,true),
  ('চোখ','Eye','eye',null,array['চক্ষু','চোখের ডাক্তার','দৃষ্টি','eye doctor']::text[],20,true),
  ('দাঁত','Dental','dental',null,array['দন্ত','দাঁতের ডাক্তার','মাড়ি','tooth']::text[],30,true),
  ('মস্তিষ্ক ও স্নায়ু','Brain & Nerve','brain-nerve',null,array['নিউরো','মাথাব্যথা','স্ট্রোক','নার্ভ']::text[],40,true),
  ('হাড় ও জয়েন্ট','Bone & Joint','bone-joint',null,array['অর্থোপেডিক','বাত','জয়েন্ট','হাড়']::text[],50,true),
  ('শিশু','Child','child',null,array['বাচ্চার ডাক্তার','শিশুরোগ','pediatric']::text[],60,true),
  ('নারী ও গর্ভাবস্থা','Women & Pregnancy','women-pregnancy',null,array['গাইনি','প্রসূতি','গর্ভাবস্থা','নারী রোগ']::text[],70,true),
  ('ত্বক','Skin','skin',null,array['চর্ম','এলার্জি','চুলকানি','skin']::text[],80,true),
  ('কিডনি ও মূত্র','Kidney & Urine','kidney-urine',null,array['কিডনি','ইউরোলজি','প্রস্রাব']::text[],90,true),
  ('পেট ও লিভার','Stomach & Liver','stomach-liver',null,array['গ্যাস্ট্রিক','লিভার','পাকস্থলী','হজম']::text[],100,true),
  ('ফুসফুস ও শ্বাসকষ্ট','Lung & Breathing','lung-breathing',null,array['বক্ষব্যাধি','হাঁপানি','শ্বাসকষ্ট','চেস্ট']::text[],110,true),
  ('ডায়াবেটিস ও হরমোন','Diabetes & Hormone','diabetes-hormone',null,array['ডায়াবেটিস','থাইরয়েড','হরমোন']::text[],120,true),
  ('মানসিক স্বাস্থ্য','Mental Health','mental-health',null,array['মনোরোগ','উদ্বেগ','ডিপ্রেশন','মানসিক']::text[],130,true),
  ('ক্যান্সার','Cancer','cancer',null,array['টিউমার','অনকোলজি','ক্যান্সার']::text[],140,true),
  ('রক্তরোগ','Blood','blood',null,array['হেমাটোলজি','রক্তস্বল্পতা','থ্যালাসেমিয়া']::text[],150,true),
  ('জ্বর ও সাধারণ রোগ','General Medicine','general-medicine',null,array['মেডিসিন','জ্বর','সাধারণ রোগ','medicine']::text[],160,true)
on conflict(slug) do update
set name_bn=excluded.name_bn,name_en=excluded.name_en,icon=excluded.icon,
    search_keywords=excluded.search_keywords,sort_order=excluded.sort_order,is_active=true;

with mappings(topic_slug,specialty_slug) as (
values
  ('heart','cardiology'),
  ('eye','ophthalmology'),
  ('dental','dentistry'),
  ('brain-nerve','neurology'),
  ('brain-nerve','neurosurgery'),
  ('bone-joint','orthopedics'),
  ('bone-joint','rheumatology'),
  ('bone-joint','physiotherapy'),
  ('child','pediatrics'),
  ('women-pregnancy','gynecology-obstetrics'),
  ('skin','dermatology'),
  ('kidney-urine','nephrology'),
  ('kidney-urine','urology'),
  ('stomach-liver','gastroenterology'),
  ('lung-breathing','pulmonology'),
  ('diabetes-hormone','endocrinology-diabetes'),
  ('mental-health','psychiatry'),
  ('cancer','oncology'),
  ('blood','hematology'),
  ('general-medicine','medicine')
)
insert into public.discovery_topic_specialties(topic_id,specialty_id)
select t.id,s.id
from mappings m
join public.discovery_topics t on t.slug=m.topic_slug
join public.specialties s on s.slug=m.specialty_slug
on conflict(topic_id,specialty_id) do nothing;

-- ------------------------------------------------------------
-- AMBULANCE RPC ACL HARDENING
-- Revoke inherited PUBLIC access and any direct anon default grant.
-- Public search is explicitly granted back below.
-- ------------------------------------------------------------
revoke execute on function public.is_verification_staff() from public,anon;
revoke execute on function public.is_ambulance_owner(uuid) from public,anon;
revoke execute on function public.can_edit_ambulance_documents(uuid) from public,anon;
revoke execute on function public.is_provider_owner(uuid) from public,anon;
revoke execute on function public.register_ambulance_service(
  text,text,text,text,text,text,text,text[],text,bigint,bigint,
  double precision,double precision,text,boolean,uuid
) from public,anon;
revoke execute on function public.update_my_ambulance_service(
  uuid,text,text,text,text,text,text,text,text[],text,bigint,bigint,
  double precision,double precision,text,boolean
) from public,anon;
revoke execute on function public.set_my_ambulance_availability(
  uuid,boolean,double precision,double precision,numeric
) from public,anon;
revoke execute on function public.request_ambulance_hospital_link(uuid,uuid)
from public,anon;
revoke execute on function public.respond_to_ambulance_hospital_link(uuid,uuid,text,text)
from public,anon;
revoke execute on function public.get_hospital_ambulance_link_requests(uuid,text)
from public,anon;
revoke execute on function public.get_ambulance_verification_queue(integer,integer)
from public,anon;
revoke execute on function public.set_ambulance_verification(uuid,text,text)
from public,anon;
revoke execute on function public.get_my_ambulance_services()
from public,anon;
revoke execute on function public.search_ambulances(
  bigint,bigint,text[],boolean,double precision,double precision,
  double precision,integer,integer
) from public,anon;

grant execute on function public.is_verification_staff()
to authenticated,service_role;
grant execute on function public.is_ambulance_owner(uuid)
to authenticated,service_role;
grant execute on function public.can_edit_ambulance_documents(uuid)
to authenticated,service_role;
grant execute on function public.is_provider_owner(uuid)
to authenticated,service_role;
grant execute on function public.register_ambulance_service(
  text,text,text,text,text,text,text,text[],text,bigint,bigint,
  double precision,double precision,text,boolean,uuid
) to authenticated,service_role;
grant execute on function public.update_my_ambulance_service(
  uuid,text,text,text,text,text,text,text,text[],text,bigint,bigint,
  double precision,double precision,text,boolean
) to authenticated,service_role;
grant execute on function public.set_my_ambulance_availability(
  uuid,boolean,double precision,double precision,numeric
) to authenticated,service_role;
grant execute on function public.request_ambulance_hospital_link(uuid,uuid)
to authenticated,service_role;
grant execute on function public.respond_to_ambulance_hospital_link(uuid,uuid,text,text)
to authenticated,service_role;
grant execute on function public.get_hospital_ambulance_link_requests(uuid,text)
to authenticated,service_role;
grant execute on function public.get_ambulance_verification_queue(integer,integer)
to authenticated,service_role;
grant execute on function public.set_ambulance_verification(uuid,text,text)
to authenticated,service_role;
grant execute on function public.get_my_ambulance_services()
to authenticated,service_role;
grant execute on function public.search_ambulances(
  bigint,bigint,text[],boolean,double precision,double precision,
  double precision,integer,integer
) to anon,authenticated,service_role;

-- ------------------------------------------------------------
-- SUPABASE STORAGE BUCKETS
-- Store only object paths in application tables, never provider-specific URLs.
-- ------------------------------------------------------------
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values
  ('avatars','avatars',true,3145728,array['image/jpeg','image/png','image/webp','image/avif']),
  ('public-images','public-images',true,5242880,array['image/jpeg','image/png','image/webp','image/avif']),
  ('verification-documents','verification-documents',false,10485760,
   array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update
set name=excluded.name,public=excluded.public,
    file_size_limit=excluded.file_size_limit,
    allowed_mime_types=excluded.allowed_mime_types;

-- Object-name rules (bucket name is not part of storage.objects.name):
-- avatars bucket: {auth.uid()}/file.ext
-- public-images bucket: {auth.uid()}/file.ext
-- verification-documents bucket: ambulances/{ambulance_id}/file.ext
drop policy if exists "public_media_read" on storage.objects;
drop policy if exists "owner_public_media_read" on storage.objects;
create policy "owner_public_media_read"
on storage.objects for select to authenticated
using (
  bucket_id in ('avatars','public-images')
  and owner_id=(select auth.uid()::text)
);

drop policy if exists "owner_public_media_insert" on storage.objects;
create policy "owner_public_media_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id in ('avatars','public-images')
  and (storage.foldername(name))[1]=auth.uid()::text
);

drop policy if exists "owner_public_media_update" on storage.objects;
create policy "owner_public_media_update"
on storage.objects for update to authenticated
using (
  bucket_id in ('avatars','public-images')
  and owner_id=auth.uid()::text
)
with check (
  bucket_id in ('avatars','public-images')
  and (storage.foldername(name))[1]=auth.uid()::text
);

drop policy if exists "owner_public_media_delete" on storage.objects;
create policy "owner_public_media_delete"
on storage.objects for delete to authenticated
using (
  bucket_id in ('avatars','public-images')
  and owner_id=auth.uid()::text
);

create or replace function public.is_verification_object_owner(p_name text)
returns boolean
language plpgsql
stable
security definer
set search_path=public,storage
as $$
declare
  parts text[];
  ambulance_uuid uuid;
begin
  parts:=storage.foldername(p_name);
  if coalesce(array_length(parts,1),0)<2 or parts[1]<>'ambulances' then
    return false;
  end if;
  ambulance_uuid:=parts[2]::uuid;
  return public.is_ambulance_owner(ambulance_uuid);
exception when invalid_text_representation then
  return false;
end;
$$;

create or replace function public.can_access_verification_object(p_name text)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select public.is_verification_object_owner(p_name)
         or public.is_verification_staff();
$$;

revoke all on function public.is_verification_object_owner(text) from public,anon;
revoke all on function public.can_access_verification_object(text) from public,anon;
grant execute on function public.is_verification_object_owner(text)
to authenticated,service_role;
grant execute on function public.can_access_verification_object(text)
to authenticated,service_role;

drop policy if exists "verification_documents_read" on storage.objects;
create policy "verification_documents_read"
on storage.objects for select to authenticated
using (
  bucket_id='verification-documents'
  and public.can_access_verification_object(name)
);

drop policy if exists "verification_documents_insert" on storage.objects;
create policy "verification_documents_insert"
on storage.objects for insert to authenticated
with check (
  bucket_id='verification-documents'
  and public.is_verification_object_owner(name)
);

drop policy if exists "verification_documents_delete" on storage.objects;
create policy "verification_documents_delete"
on storage.objects for delete to authenticated
using (
  bucket_id='verification-documents'
  and owner_id=auth.uid()::text
  and public.is_verification_object_owner(name)
);

-- ------------------------------------------------------------
-- REFERENCE-DATA HEALTH RPC
-- ------------------------------------------------------------
create or replace function public.get_reference_data_health()
returns jsonb
language sql
stable
security definer
set search_path=public
as $$
  select jsonb_build_object(
    'divisions',(select count(*) from public.divisions where is_active),
    'districts',(select count(*) from public.districts where is_active),
    'upazilas',(select count(*) from public.upazilas where is_active),
    'sirajganj_upazilas',(
      select count(*)
      from public.upazilas u
      join public.districts d on d.id=u.district_id
      where d.slug='sirajganj' and u.is_active
    ),
    'specialties',(select count(*) from public.specialties where is_active),
    'discovery_topics',(select count(*) from public.discovery_topics where is_active),
    'storage_buckets',(
      select count(*) from storage.buckets
      where id in ('avatars','public-images','verification-documents')
    )
  );
$$;

revoke all on function public.get_reference_data_health() from public,anon;
grant execute on function public.get_reference_data_health()
to authenticated,service_role;

-- ------------------------------------------------------------
-- FAIL-FAST MIGRATION ASSERTIONS
-- ------------------------------------------------------------
do $$
declare
  health jsonb;
begin
  health:=public.get_reference_data_health();
  if (health->>'divisions')::integer<8 then
    raise exception 'Step 11 failed: division seed incomplete';
  end if;
  if (health->>'districts')::integer<64 then
    raise exception 'Step 11 failed: district seed incomplete';
  end if;
  if (health->>'upazilas')::integer<495 then
    raise exception 'Step 11 failed: upazila seed incomplete';
  end if;
  if (health->>'sirajganj_upazilas')::integer<>9 then
    raise exception 'Step 11 failed: Sirajganj must have exactly 9 seeded upazilas';
  end if;
  if (health->>'specialties')::integer<26 then
    raise exception 'Step 11 failed: specialty seed incomplete';
  end if;
  if (health->>'discovery_topics')::integer<16 then
    raise exception 'Step 11 failed: discovery topic seed incomplete';
  end if;
  if (health->>'storage_buckets')::integer<>3 then
    raise exception 'Step 11 failed: storage bucket setup incomplete';
  end if;
end;
$$;

-- ============================================================
-- END STEP 11
-- ============================================================
