import { useEffect, useMemo, useState } from 'react';
import { Building2, CalendarDays, ExternalLink, LoaderCircle, MapPin, Phone, Star } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import FollowSaveButton from '../components/FollowSaveButton';
import PublicHeader from '../components/PublicHeader';
import StructuredReviewSection from '../components/StructuredReviewSection';
import VisitorBottomNav from '../components/VisitorBottomNav';
import { getImageUrl } from '../lib/storage';
import { getDoctorsForProvider, getPublicProviderBySlug } from '../services/discovery';
import { providerGallery, providerInvestigationCosts, providerReviews, providerServices, providerSlider, providerTreatmentCosts, type ProviderCost, type ProviderGalleryImage, type ProviderReview, type ProviderService, type ProviderSliderImage } from '../services/providerWebsiteContent';
import { getProviderPublicStats, recordProviderInteraction } from '../services/engagement';
import type { DoctorSearchRow, ProviderDirectoryRow, PublicProfileStats } from '../types';

const text=(v:{bn?:string;en?:string}|null|undefined,lang:'bn'|'en')=>v?.[lang]||v?.bn||v?.en||'';
const media=(path:string|null|undefined)=>getImageUrl(path,'public-images')||path||'';

export default function ProviderWebsitePage(){
  const {slug=''}=useParams(); const [lang,setLang]=useState<'bn'|'en'>('bn');
  const [provider,setProvider]=useState<ProviderDirectoryRow|null>(null); const [doctors,setDoctors]=useState<DoctorSearchRow[]>([]); const [providerStats,setProviderStats]=useState<PublicProfileStats|null>(null);
  const [services,setServices]=useState<ProviderService[]>([]); const [gallery,setGallery]=useState<ProviderGalleryImage[]>([]); const [slider,setSlider]=useState<ProviderSliderImage[]>([]); const [reviews,setReviews]=useState<ProviderReview[]>([]); const [treatment,setTreatment]=useState<ProviderCost[]>([]); const [investigation,setInvestigation]=useState<ProviderCost[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [slide,setSlide]=useState(0);
  useEffect(()=>{ let alive=true; (async()=>{ try{ setLoading(true); const p=await getPublicProviderBySlug(slug); if(!p){ if(alive)setProvider(null); return; } const [d,s,g,sl,r,t,i,stats]=await Promise.all([getDoctorsForProvider(p.id),providerServices.getAll(p.id,true),providerGallery.getAll(p.id,true),providerSlider.getAll(p.id,true),providerReviews.getAll(p.id,true),providerTreatmentCosts.getAll(p.id),providerInvestigationCosts.getAll(p.id),getProviderPublicStats(p.id).catch(()=>null)]); if(!alive)return; setProvider(p);setDoctors(d);setServices(s);setGallery(g);setSlider(sl);setReviews(r.filter((review)=>review.review_source!=='patient'));setTreatment(t);setInvestigation(i);setProviderStats(stats);}catch(e){if(alive)setError(e instanceof Error?e.message:'ডেটা লোড করা যায়নি');}finally{if(alive)setLoading(false);} })(); return()=>{alive=false};},[slug]);
  useEffect(()=>{ if(!provider?.id)return; void recordProviderInteraction(provider.id,'profile_view','provider_website').catch(()=>undefined); },[provider?.id]);
  useEffect(()=>{ if(slider.length<2)return; const id=window.setInterval(()=>setSlide(v=>(v+1)%slider.length),5000); return()=>clearInterval(id);},[slider.length]);
  const hero=useMemo(()=> slider[slide]?.image ? media(slider[slide].image) : media(provider?.banner_url),[slider,slide,provider]);
  if(loading)return <div className="app-shell"><PublicHeader mobileBottomNav/><main className="container loading-box"><LoaderCircle className="spin"/> Website লোড হচ্ছে…</main></div>;
  if(error||!provider)return <div className="app-shell"><PublicHeader mobileBottomNav/><main className="container provider-site-empty"><Building2/><h1>প্রতিষ্ঠান পাওয়া যায়নি</h1><p>{error||'এই website শুধু approved এবং verified প্রতিষ্ঠানের জন্য উপলভ্য।'}</p><Link to="/providers">প্রতিষ্ঠানের তালিকায় ফিরুন</Link></main></div>;
  return <div className="app-shell provider-site"><PublicHeader mobileBottomNav/><main>
    <section className="provider-site-hero" style={hero?{backgroundImage:`linear-gradient(90deg,rgba(3,41,37,.86),rgba(3,41,37,.35)),url(${hero})`}:undefined}><div className="container provider-site-hero-inner"><div className="provider-site-logo">{provider.logo_url?<img src={media(provider.logo_url)} alt=""/>:<Building2/>}</div><div><span>{provider.provider_type==='hospital'?'Hospital':'Chamber'} • Verified</span><h1>{lang==='bn'?provider.name_bn:(provider.name_en||provider.name_bn)}</h1><p>{slider[slide]?text(slider[slide].caption,lang):(provider.short_description||'')}</p><div className="provider-site-actions">{provider.phone&&<a href={`tel:${provider.phone}`} onClick={()=>void recordProviderInteraction(provider.id,'call_click','provider_website').catch(()=>undefined)}><Phone/> {provider.phone}</a>}{doctors[0]&&<Link to={`/doctors/${doctors[0].doctor_id}/book?provider=${provider.id}`} onClick={()=>void recordProviderInteraction(provider.id,'appointment_click','provider_website').catch(()=>undefined)}><CalendarDays/> Appointment</Link>}<FollowSaveButton targetType="provider" targetId={provider.id} stats={providerStats} variant="button" entityLabel={provider.provider_type==='hospital'?'হাসপাতাল':'চেম্বার'} onStatsChange={setProviderStats}/></div><div className="provider-site-followers"><b>{(providerStats?.follower_count??0).toLocaleString('bn-BD')}</b> {lang==='bn'?'মোট অনুসারী':'followers'}</div></div><button className="provider-lang" onClick={()=>setLang(lang==='bn'?'en':'bn')}>{lang==='bn'?'EN':'বাংলা'}</button></div></section>
    <div className="container provider-site-body">
      <section className="provider-site-section"><h2>{lang==='bn'?'আমাদের সম্পর্কে':'About'}</h2><p>{(lang==='bn'?(provider.about_bn||provider.short_description||provider.about_en):(provider.about_en||provider.about_bn||provider.short_description))|| (lang==='bn'?'প্রতিষ্ঠানের বিস্তারিত তথ্য শিগগিরই যোগ হবে।':'More information will be added soon.')}</p><div className="provider-info-grid"><span><MapPin/>{provider.address||'—'}</span>{provider.opening_note&&<span>{provider.opening_note}</span>}{provider.map_url&&<a href={provider.map_url} target="_blank" rel="noreferrer" onClick={()=>void recordProviderInteraction(provider.id,'map_click','provider_website').catch(()=>undefined)}><ExternalLink/> Map</a>}</div></section>
      <section className="provider-site-section"><h2>{lang==='bn'?'ডাক্তারবৃন্দ':'Doctors'}</h2>{doctors.length?<div className="provider-doctor-grid">{doctors.map(d=><article key={d.doctor_id}>{d.avatar_url?<img src={getImageUrl(d.avatar_url,'public-images')||d.avatar_url} alt=""/>:<div className="doctor-placeholder">DR</div>}<h3>{d.doctor_name}</h3><p>{d.degree||d.designation||''}</p><Link to={`/doctors/${d.doctor_id}`}>Profile</Link>{provider.phone&&<a href={`tel:${provider.phone}`} onClick={()=>void recordProviderInteraction(provider.id,'call_click','provider_doctor_card').catch(()=>undefined)}>Call</a>}{(provider.whatsapp||provider.phone)&&<a href={`https://wa.me/${(provider.whatsapp||provider.phone||'').replace(/\D/g,'').replace(/^0/,'88')}`} target="_blank" rel="noreferrer" onClick={()=>void recordProviderInteraction(provider.id,'whatsapp_click','provider_doctor_card').catch(()=>undefined)}>WhatsApp</a>}</article>)}</div>:<p className="provider-empty">কোনো linked doctor এখনো যোগ করা হয়নি।</p>}</section>
      <section className="provider-site-section"><h2>{lang==='bn'?'সেবাসমূহ':'Services'}</h2>{services.length?<div className="provider-content-grid">{services.map(x=><article key={x.id}>{x.image&&<img src={media(x.image)} alt=""/>}<h3>{text(x.name,lang)}</h3><p>{text(x.description,lang)}</p></article>)}</div>:<p className="provider-empty">কোনো service যোগ করা হয়নি।</p>}</section>
      <section className="provider-site-section"><h2>{lang==='bn'?'গ্যালারি':'Gallery'}</h2>{gallery.length?<div className="provider-gallery-public">{gallery.map(x=><figure key={x.id}>{x.image&&<img src={media(x.image)} alt={text(x.caption,lang)}/>}<figcaption>{text(x.caption,lang)}</figcaption></figure>)}</div>:<p className="provider-empty">কোনো gallery image নেই।</p>}</section>
      <StructuredReviewSection targetType="provider" targetId={provider.id} entityLabel={provider.provider_type==='hospital'?'হাসপাতাল':'চেম্বার'} language={lang} />
      {reviews.length?<section className="provider-site-section"><h2>{lang==='bn'?'প্রতিষ্ঠানের প্রকাশিত মতামত':'Published testimonials'}</h2><div className="provider-review-grid">{reviews.map(x=><article key={x.id}><div>{Array.from({length:x.rating}).map((_,i)=><Star key={i}/>)}</div><h3>{x.name}</h3><p>{text(x.text,lang)||x.comment||''}</p>{x.reply&&<small>Reply: {text(x.reply,lang)}</small>}</article>)}</div></section>:null}
      <section className="provider-site-section"><h2>{lang==='bn'?'খরচের তালিকা':'Costs'}</h2><div className="provider-cost-columns"><CostList title={lang==='bn'?'চিকিৎসা':'Treatment'} rows={treatment} lang={lang}/><CostList title={lang==='bn'?'পরীক্ষা':'Investigation'} rows={investigation} lang={lang}/></div></section>
      <section className="provider-site-section provider-contact"><h2>{lang==='bn'?'যোগাযোগ':'Contact'}</h2><p>{provider.address}</p>{provider.phone&&<a href={`tel:${provider.phone}`} onClick={()=>void recordProviderInteraction(provider.id,'call_click','provider_website').catch(()=>undefined)}>{provider.phone}</a>}{provider.whatsapp&&<a href={`https://wa.me/${provider.whatsapp.replace(/\D/g,'')}`} target="_blank" rel="noreferrer" onClick={()=>void recordProviderInteraction(provider.id,'whatsapp_click','provider_website').catch(()=>undefined)}>WhatsApp</a>}{provider.website_url&&<a href={provider.website_url} target="_blank" rel="noreferrer">Official website</a>}</section>
    </div>
  </main><VisitorBottomNav/></div>;
}
function CostList({title,rows,lang}:{title:string;rows:ProviderCost[];lang:'bn'|'en'}){return <div><h3>{title}</h3>{rows.length?<table><tbody>{rows.map(r=><tr key={r.id}><td>{text(r.name,lang)}</td><td>{text(r.cost,lang)}</td></tr>)}</tbody></table>:<p className="provider-empty">কোনো তথ্য নেই।</p>}</div>}
