import { MessageCircle } from 'lucide-react';
import ProviderWebsiteContentTabs, { type ProviderCostMode, type ProviderWebsiteTab } from '../../../components/ProviderWebsiteContentTabs';
import ProviderProfilePage from '../../../pages/ProviderProfilePage';
import { HospitalPageHeader } from '../HospitalShell';
import { bi, type HospitalCopy, useHospitalLanguage } from '../i18n';
import { useHospital } from '../useHospital';

export function HospitalInformationPage(){return <><HospitalPageHeader eyebrow={bi('হাসপাতালের পরিচয়','Hospital Identity')} title={bi('হাসপাতালের তথ্য','Hospital Information')} description={bi('পাবলিক তথ্য, যোগাযোগ, লোকেশন, লোগো ও প্রোফাইল কনটেন্ট পরিচালনা করুন।','Manage public information, contact details, location, logo and profile content.')}/><ProviderProfilePage hideWebsiteContent hidePublicProfileLink/></>}

export function HospitalPublicProfileManagementPage(){return <HospitalInformationPage/>}

function Content({title,description,tab,costMode}:{title:HospitalCopy;description:HospitalCopy;tab:ProviderWebsiteTab;costMode?:ProviderCostMode}){const{provider,loading,error}=useHospital();const{text}=useHospitalLanguage();return <><HospitalPageHeader eyebrow={bi('পাবলিক হাসপাতাল কনটেন্ট','Public Hospital Content')} title={title} description={description}/>{error&&<div className="hospital-error">{error}</div>}{loading?<div className="hospital-empty">{text(bi('হাসপাতাল লোড হচ্ছে…','Loading Hospital…'))}</div>:provider?<section className="hospital-panel"><ProviderWebsiteContentTabs providerId={provider.id} initialTab={tab} hideNavigation costMode={costMode}/></section>:<div className="hospital-empty">{text(bi('আগে হাসপাতাল প্রোফাইল তৈরি করুন।','Create the Hospital profile first.'))}</div>}</>}
export function HospitalServicesPage(){return <Content title={bi('সেবা ম্যানেজমেন্ট','Services Management')} description={bi('পাবলিক হাসপাতাল সেবা ও খোলার সময় পরিচালনা করুন।','Manage public Hospital services and opening hours.')} tab="services"/>}
export function HospitalTreatmentCostsPage(){return <Content title={bi('চিকিৎসা খরচ ম্যানেজমেন্ট','Treatment Cost Management')} description={bi('চিকিৎসা ও সেবার স্বচ্ছ খরচের তথ্য বজায় রাখুন।','Maintain transparent treatment and service cost information.')} tab="costs" costMode="treatment"/>}
export function HospitalInvestigationCostsPage(){return <Content title={bi('পরীক্ষার খরচ ম্যানেজমেন্ট','Investigation Cost Management')} description={bi('পরীক্ষা ও ডায়াগনস্টিক খরচের তথ্য বজায় রাখুন।','Maintain investigation and diagnostic cost information.')} tab="costs" costMode="investigation"/>}

export function HospitalReceptionSettingsPage(){return <><HospitalPageHeader eyebrow={bi('ডিফল্ট ডাক্তার যোগাযোগ','Default Doctor Contact')} title={bi('রিসেপশন সেটিংস','Reception Settings')} description={bi('ব্যক্তিগত যোগাযোগ চালু না থাকলে হাসপাতালের ফোন ও WhatsApp প্রতিটি ডাক্তারের ডিফল্ট যোগাযোগ হবে।','Hospital phone and WhatsApp are each Doctor’s default contact unless an individual override is enabled.')}/><ProviderProfilePage/></>}
export function HospitalSettingsPage(){return <><HospitalPageHeader eyebrow={bi('হাসপাতাল কনসোল','Hospital Console')} title={bi('সেটিংস','Settings')} description={bi('অন্য role পরিবর্তন না করে হাসপাতাল প্রোফাইল ও অ্যাকাউন্ট কনফিগারেশন পরিচালনা করুন।','Manage Hospital profile and account configuration without changing other platform roles.')}/><ProviderProfilePage/></>}
export function HospitalSupportPage(){const{provider}=useHospital();const{text}=useHospitalLanguage();return <><HospitalPageHeader eyebrow={bi('সহায়তা ও সাপোর্ট','Help & Support')} title={bi('হাসপাতাল সাপোর্ট','Hospital Support')} description={bi('ভেরিফিকেশন, কনটেন্ট, রিসেপশন অ্যাপয়েন্টমেন্ট বা কারিগরি বিষয়ে সহায়তা নিন।','Get help with verification, content, reception appointments or technical issues.')}/><section className="hospital-panel"><div className="hospital-panel-title"><div><h2>{text(bi('সাপোর্টে যোগাযোগের আগে','Before contacting support'))}</h2><p>{text(bi('সমস্যা দ্রুত শনাক্ত করতে Hospital ID উল্লেখ করুন।','Include the Hospital ID so the issue can be traced safely.'))}</p></div><MessageCircle/></div><p><strong>{text(bi('হাসপাতাল:','Hospital:'))}</strong> {provider?.name_bn||text(bi('তৈরি হয়নি','Not created'))}</p><p><strong>Hospital ID:</strong> {provider?.id||'—'}</p></section></>}
