import { type FormEvent, useEffect, useState } from 'react';
import { LoaderCircle, Pencil, Plus, Save, Trash2, Users, X } from 'lucide-react';
import { HospitalPageHeader } from '../HospitalShell';
import { bi, useHospitalLanguage } from '../i18n';
import { deleteMyHospitalStaff, getMyHospitalStaff, saveMyHospitalStaff } from '../services/hospitalStaff';
import type { HospitalStaffMember } from '../types';
import { useHospital } from '../useHospital';

const blank = { id:null as string|null,full_name:'',designation:'',department:'',phone:'',email:'',notes:'',is_active:true };

export default function HospitalStaffPage() {
  const { text } = useHospitalLanguage();
  const { provider } = useHospital();
  const [rows,setRows]=useState<HospitalStaffMember[]>([]);
  const [form,setForm]=useState(blank);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState<string|null>(null);
  async function load(){if(provider)setRows(await getMyHospitalStaff(provider.id));}
  useEffect(()=>{void load().catch((reason)=>setError(reason instanceof Error?reason.message:text(bi('স্টাফ তালিকা লোড করা যায়নি।','Staff could not be loaded.'))));},[provider?.id]);
  async function submit(event:FormEvent){event.preventDefault();if(!provider)return;setBusy(true);setError(null);try{await saveMyHospitalStaff(provider.id,{...form,provider_id:provider.id,designation:form.designation||null,department:form.department||null,phone:form.phone||null,email:form.email||null,notes:form.notes||null} as HospitalStaffMember);setForm(blank);await load();}catch(reason){setError(reason instanceof Error?reason.message:text(bi('স্টাফ তথ্য সংরক্ষণ করা যায়নি।','Staff could not be saved.')));}finally{setBusy(false)}}
  function edit(row:HospitalStaffMember){setForm({id:row.id,full_name:row.full_name,designation:row.designation||'',department:row.department||'',phone:row.phone||'',email:row.email||'',notes:row.notes||'',is_active:row.is_active});window.scrollTo({top:0,behavior:'smooth'})}
  async function remove(id:string){if(!provider||!window.confirm(text(bi('এই স্টাফ রেকর্ড মুছবেন?','Delete this staff directory record?'))))return;try{await deleteMyHospitalStaff(provider.id,id);await load();}catch(reason){setError(reason instanceof Error?reason.message:text(bi('স্টাফ রেকর্ড মোছা যায়নি।','Staff could not be deleted.')))}}
  return <><HospitalPageHeader eyebrow={bi('হাসপাতাল পরিচালনা','Hospital Operations')} title={bi('স্টাফ ম্যানেজমেন্ট','Staff Management')} description={bi('হাসপাতালের অভ্যন্তরীণ স্টাফ ডিরেক্টরি পরিচালনা করুন। এটি কোনো login account বা platform role তৈরি করে না।','Maintain an internal Hospital staff directory without creating login accounts or changing platform roles.')} action={<button type="button" onClick={()=>setForm(blank)}><Plus/> {text(bi('নতুন স্টাফ','New Staff'))}</button>}/>{error&&<div className="hospital-error">{error}</div>}
    <form className="hospital-panel hospital-form" onSubmit={submit}><div className="hospital-panel-title"><div><h2>{form.id?text(bi('স্টাফ সম্পাদনা','Edit staff')):text(bi('স্টাফ যোগ করুন','Add staff member'))}</h2></div>{form.id&&<button className="hospital-secondary-button" type="button" onClick={()=>setForm(blank)}><X/></button>}</div><div className="hospital-form-grid"><label>{text(bi('পূর্ণ নাম *','Full name *'))}<input required minLength={2} value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>{text(bi('পদবি','Designation'))}<input value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></label><label>{text(bi('বিভাগ','Department'))}<input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></label><label>{text(bi('ফোন','Phone'))}<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> {text(bi('সক্রিয় স্টাফ রেকর্ড','Active staff record'))}</span></label></div><label>{text(bi('নোট','Notes'))}<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="hospital-primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Save/>} {text(bi('স্টাফ সংরক্ষণ করুন','Save staff'))}</button></form>
    <section className="hospital-panel" style={{marginTop:18}}><div className="hospital-panel-title"><div><h2>{text(bi('স্টাফ ডিরেক্টরি','Staff directory'))}</h2><p>{rows.length} {text(bi('টি রেকর্ড','records'))}</p></div><Users/></div>{rows.map(row=><article className="hospital-list-row" key={row.id}><div><h3>{row.full_name}</h3><p>{[row.designation,row.department].filter(Boolean).join(' • ')||text(bi('দায়িত্ব যোগ করা হয়নি','Role not added'))}</p><small>{row.phone||row.email||text(bi('যোগাযোগ যোগ করা হয়নি','No contact added'))} • {row.is_active?text(bi('সক্রিয়','Active')):text(bi('নিষ্ক্রিয়','Inactive'))}</small></div><div className="hospital-doctor-card-actions"><button type="button" onClick={()=>edit(row)}><Pencil/></button><button className="danger" type="button" onClick={()=>void remove(row.id)}><Trash2/></button></div></article>)}{!rows.length&&<div className="hospital-empty">{text(bi('কোনো স্টাফ রেকর্ড যোগ করা হয়নি।','No staff record added.'))}</div>}</section>
  </>;
}
