import { Building2, ExternalLink, MessageCircle, Settings } from 'lucide-react';
import { Link } from 'react-router-dom';
import ProviderWebsiteContentTabs, { type ProviderWebsiteTab } from '../../../components/ProviderWebsiteContentTabs';
import ProviderProfilePage from '../../../pages/ProviderProfilePage';
import { HospitalPageHeader } from '../HospitalShell';
import { useHospital } from '../useHospital';

export function HospitalInformationPage(){return <><HospitalPageHeader eyebrow="Hospital Identity" title="Hospital Information" description="Manage public information, contact details, location, logo and profile content."/><ProviderProfilePage/></>}

export function HospitalPublicProfileManagementPage(){const{provider}=useHospital();return <><HospitalPageHeader eyebrow="Visitor-facing Hospital Profile" title="Public Profile Management" description="Preview the verified public Hospital profile and manage the content visitors can see." action={provider?<Link to={`/hospital/${provider.id}`} target="_blank"><ExternalLink/> Open profile</Link>:undefined}/><section className="hospital-grid hospital-action-grid"><Link className="hospital-action-card" to="/hospital-console/information"><span><Building2/></span><div><strong>Hospital information</strong><small>Identity, contact, about and location</small></div></Link><Link className="hospital-action-card" to="/hospital-console/gallery"><span><ExternalLink/></span><div><strong>Top gallery</strong><small>Four premium public images</small></div></Link><Link className="hospital-action-card" to="/hospital-console/services"><span><Settings/></span><div><strong>Public services</strong><small>Services, hours and costs</small></div></Link></section></>}

function Content({title,description,tab}:{title:string;description:string;tab:ProviderWebsiteTab}){const{provider,loading,error}=useHospital();return <><HospitalPageHeader eyebrow="Public Hospital Content" title={title} description={description}/>{error&&<div className="hospital-error">{error}</div>}{loading?<div className="hospital-empty">Loading Hospital…</div>:provider?<section className="hospital-panel"><ProviderWebsiteContentTabs providerId={provider.id} initialTab={tab} hideNavigation/></section>:<div className="hospital-empty">Create the Hospital profile first.</div>}</>}
export function HospitalServicesPage(){return <Content title="Services Management" description="Manage public Hospital services and opening hours." tab="services"/>}
export function HospitalTreatmentCostsPage(){return <Content title="Treatment Cost Management" description="Maintain transparent treatment and service cost information." tab="costs"/>}
export function HospitalInvestigationCostsPage(){return <Content title="Investigation Cost Management" description="Maintain investigation and diagnostic cost information." tab="costs"/>}

export function HospitalReceptionSettingsPage(){return <><HospitalPageHeader eyebrow="Default Doctor Contact" title="Reception Settings" description="Hospital reception phone and WhatsApp are the default contact for every Doctor unless an individual contact override is enabled."/><ProviderProfilePage/></>}
export function HospitalSettingsPage(){return <><HospitalPageHeader eyebrow="Hospital Console" title="Settings" description="Manage Hospital profile and account-facing configuration without changing other platform roles."/><ProviderProfilePage/></>}
export function HospitalSupportPage(){const{provider}=useHospital();return <><HospitalPageHeader eyebrow="Help & Support" title="Hospital Support" description="Get help with Hospital verification, content, reception appointments or technical issues."/><section className="hospital-panel"><div className="hospital-panel-title"><div><h2>Before contacting support</h2><p>Include the Hospital identifier so the issue can be traced safely.</p></div><MessageCircle/></div><p><strong>Hospital:</strong> {provider?.name_bn||'Not created'}</p><p><strong>Hospital ID:</strong> {provider?.id||'—'}</p><p>For account or technical support, use the official contact information published by the platform administrator. Doctor support chat is intentionally not reused by this independent module.</p></section></>}
